- README.en-us.md
- README.md
- docs/progress/index.en-us.md
- docs/progress/index.md
- src/progress/view/progress.jsx
progress percent 99.8
shown as 100%, for Math.round(99.8) === 100
now fixed:
99.8 -> 99 for  Math.floor(99.8) === 99
add Dingtalk group qrcode to reademe.md
> Fix progress number precise and add Dingtalk group qrcode

- src/menu/view/group.jsx
- test/menu/index-spec.js
Group.Item cant pass custom className
> fix(Menu): Group.Item cant pass custom className

- package.json
- src/util/string.js
Hello, when I excute `npm run dev`, the terminal hints md5 module isn't install, so I add it into `package.json`:
Also, `npm run dev` script seems not to be compatible with git bash on windows 10, those markdown files under `/docs` can't be parsed correctly. Finally I have to use WSL to run this project.
> chore(*): fix typo in comments & add md5 dev dependency

- src/upload/upload.jsx
When limit is set,  exceeding limit will cause upload disabled.
so disable delete file when disabled will result in failing delete file when reaching limit.
-----------
之前修复了一个bug,就是 禁止disable状态下删除文件。
但是后来发现, 在设置了limit以后,会触发组件disable。 
例如limit = 2的时候, 传了两个文件以后就不可以删除文件了。而现在很多线上的组件都是这么用的，所以先回滚这个特性。
> fix(Upload): allow remove file when disabled

- docs/tab/index.en-us.md
- docs/tab/index.md
- src/tab/tab.jsx
- src/tab/tabs/tab-item.jsx
- test/tab/index-spec.js
The component actually only processes Element child, as in line 33 of https://github.com/alibaba-fusion/next/blob/master/src/tab/tabs/utils.js , so this patch use the same logic to prevent  'child.props.disabled' from causing 'no "disabled" property of undefined' error, which prevents rendering the whole tab.
> fix(Tab): can not render when child have null item

- src/table/base/cell.jsx
error occurs when set props 'style' and 'align' both on Table.Column.
> fix(Table): style conflict with align

- src/select/base.jsx
- test/select/index-spec.js
Select 组件开启virtual和showSearch之后，当filter出空dataSource时抛异常。
简单判断children.length为0，关闭virtual
> fix(Select): fix Select with useVirtual when empty dataSource

- src/tab/tab.jsx
- src/tab/tabs/nav.jsx
最好在下个Y位去掉，这里添加支持只是为了那些有可能升级js包，但是不升级样式包的用户，并且rtl的支持很有限，这里只是简单处理
> fix(Tab): shallow rtl support

- package.json
- test/progress/index-spec.js
- test/util/a11y.js
- Uses `axe-core` library (same library used by Chrome DevTools)
- Must import styles directly to be able to test for things like color contrast
- Unit tests will only test for major violations using `results.violations.length === 0`. The other test results are warnings or require manual checking. It would be good in the future to have such results included in CI reports.
- created a11y unit test util functions to make testing easier
- Should have at least 1 test for each major component type
- Ex. <Progress /> and <Progress shape="circle" /> are separate subcomponents and should each have their own test
> A11y unit tests

- package.json
- scripts/server/loaders/demo/index.js
- scripts/server/server.js
- scripts/server/webpack.js
- uses `react-axe` which is built on `axe-core`
- pass `a11y=true` after the component name to report a11y issues. Defaults to off
- Ex. `npm run dev Button a11y=true`
- Causes compile time to be much longer.
- has nice reporting to console
> Run automated A11y tests with Axe-core during development

- src/number-picker/index.jsx
- src/select/main.scss
- src/select/select.jsx
- test/number-picker/index-spec.js
- NumberPicker: fix set value to min while value < min by click +
- Select: fix double trigger onVisibleChange bug
example:
- NumberPicker: https://riddle.alibaba-inc.com/riddles/8c721dc3
- Select: https://riddle.alibaba-inc.com/riddles/70f10d49
> Bugfix: NumberPicker not work while value<min/ Select double onVisibleChange trigged

- docs/search/index.en-us.md
- docs/search/index.md
- src/search/Search.jsx
- test/search/index-spec.js
When disabled props put on Search, the Input in will be disabled but the button and filter won't.
this pr fix it;
---
之前的版本,设置search的 disabled= true, search里面的input被disable,但是button没有被disable。现在修复这个问题
> fix(Search): disable not work

- src/select/select.jsx
- test/select/index-spec.js
should not change display text, while under controlled
```
<Select id="basic-demo" value={'frank'} >
<Option value="jack">Jack</Option>
<Option value="frank">Frank</Option>
<Option value="hugo">Hugo</Option>
</Select>
```
text should always be frank, while select options
> fix(Select): display text should not change while under controlled

- src/util/string.js
- test/util/string-spec.js
This PR is trying to resolve some **BREAKCHANGE**-like problems that caused by new features from **1.12.0** release.
In **1.12.0**, there has a bunch of features was added for enhance component's accessibilities, and that 's amazing job by the **next** team. But, there has a few problems in actual use. Especially for library maintainers who depend on **next** library, these problems are fatal:
Some components added new i18n messages and process them for a11y props, but missing a check for i18n messages compatibility. I'm maintaining a library which manage i18n messages in a centralized service. These messages should be stable and only changed on necessary. But the messages that added by new release has broken the status quo.
https://github.com/alibaba-fusion/next/blame/build/1.12.0/src/pag …
> fix(Util): DO NOT process any non-string type value

- test/collapse/a11y-spec.js
- test/progress/a11y-spec.js
- test/util/a11y/checks.js
- test/util/a11y/validate.js
helper utils for a11y unit testing
- devs will be able to create a11y unit tests based on what an element is supposed to be
- generic `tagName` and `roleType` checks
- composite `isButton` and `isHeading` checks that use `roleType` and `tagName`
- checks allow for selectors, or ReactWrapper, DOMComponents
- allow axe tests to run on any dom node
- update existing tests to reflect the change
- move and rename `a11y.js` util to `validate.js`
> Test: A11y - helper utils for a11y unit testing

- README.md
- README.zh-cn.md
增加文档
`@alifd/next` 配合 [Fusion Design](https://fusion.design) 解决在页面开发时设计师和前端协同的问题。通过这套体系设计师可以自由的定制组件的 UI 并产出一个 npm 主题包，前端可以直接使用这个主题包不需要关注组件的还原度问题。省去了和设计师反复的去做还原度 Review 的工作量，大幅度的提高了开发效率。
`@alifd/next` usually used with [Fusion Design](https://fusion.design) to improving designer-developer collaboration and development efficiency. Designer can customize the UI of components and release an npm theme package. Developer can use this theme package directly, and don't need to care about the UI refactoring. It saves the workload of reductive degree review repeatedly with designers, and greatly improves the development efficiency.
> docs(*): update readme

- src/table/expanded.jsx
- src/table/expanded/row.jsx
- test/table/index-spec.js
这两个函数里的index增长步长是2，应该是1。
具体表现是函数里的index打印出来是0，2，4，6，期望是1，2，3，4，看起来是0.x到1.x迁移引起的
原因在这一行 https://github.com/alibaba-fusion/next/blob/master/src/table/expanded.jsx#L169
close https://github.com/alibaba-fusion/next/issues/318
> fix(Table): correct index in expandedRowRender and getExpandedColProps

- docs/field/demo/dynamic.md
- docs/field/demo/validator.md
- docs/field/index.en-us.md
- docs/field/index.md
- docs/form/index.en-us.md
- docs/form/index.md
- src/field/index.js
- src/form/enhance.jsx
- src/form/form.jsx
- src/form/item.jsx
- test/field/index-spec.js
- test/field/options-spec.js
- test/form/validate-spec.js
1. 处理 parseName 后数组删除后数据错位的问题，老版本必须指定全局唯一key，现在通过spliceArray来删除一个类似name.{index} 的key后，其他的key会自动 -1 来订正数组序列。
To deal with the problem of data misalignment after deletion of arrays.
in old version it must  to specify a global unique key.  Now, after deleting a key similar to name. {index} through spliceArray, the other keys will automatically - 1 to correct the array sequence.
value like
```
a.0 = 0
a.1 = 1
a.2 = 2
```
after delete a.0 by remove('a.0')
```
a.1 = 1
a.2 = 2
```
after delete a.0 by spliceArray('a.{index}', 0)
```
a.0 = 1
a.1 = 2
```
2. autoValidate=false 关闭自动校验 / use autoValidate=false to close auto validate by onChange
useg:
for all components
```
field = new Field(this, {autoValidate: false})
```
for single component
```
field = new Field(this)
field.init('name', …
```
> feat(Field): api spliceArray to splice Array like name.{index} / api autoValidate=false to close onChange validate

- src/message/main.scss
- src/overlay/utils/position.js
- src/range/view/range.jsx
- Positioned `Overlay` components should always use offsets if given. 
- Range Tooltips should not attempt to adjust the tooltip location to remain in the viewport
- Message fixed styles are not needed anywhere in the code base as no `.next-message` class has a nested `.next-message-wrapper` class.
> fix(*): use offset when positioning overlay, do not adjust range tooltip

- test/util/a11y/validate.js
I added some time delay before a11y test, it passed in my fork https://travis-ci.com/youluna/next/builds/103822265
> chore(*): make sure rendering done before a11y test

- src/tag/main.scss
- src/tag/scss/mixin.scss
- set max width for the body to make sure the close button appears
- increase the icon left margin to not trigger the ellipses unnecessarily
> fix(Tag): close button not showing in select when text too long

- src/util/log.js
Only print warnings on development environment, and prevent this behavior on production.
> fix(Util): Prevent warning on production

- docs/nav/theme/index.jsx
- src/menu/main.scss
- src/nav/main.scss
- src/nav/scss/mixin.scss
- 移除focus样式。当前focus样式同hover样式完全一样，会给正常使用的用户带来困扰。
- 修复menu配置demo的bug
> fix(Nav): remove focus style which equals to hover

- src/balloon/balloon.jsx
> fix(Balloon): strengthen robustness for align, close#517

- docs/tab/demo/excess-mode.md
- docs/tab/demo/extra.md
- docs/tab/index.en-us.md
- src/tab/main.scss
- src/tab/rtl.scss
- src/tab/tabs/nav.jsx
- test/tab/index-spec.js
CAUSION: 重大改动
现在prev和next的disable和enable的状态将和navbar的offset一样只是组件的样式，不再是组件的内部状态，不触发重新渲染。同时组件update时开启auto scroll to active tab的功能，即自动将”半进入“可见区域的tab自动滚动到可见区内，这个滚动只会带来prev和next的样式变化，所以可以放心开启。从根本上解决了：
#429 #226 以及 http://fusion-image.oss-cn-beijing.aliyuncs.com/test/bug.mov
> fix(Tab): slide related issues

- src/tab/main.scss
- src/tab/rtl.scss
As in the title, capsule tab shakes when switching, this pr fixed that by removing margin(left/right) from  transition, i.e. override `transition: all .4s $ease-out-quint` with specific properties that we want to see transition on.
It also fixes incorrect capsule border in rtl mode.
> fix(Tab): capsule tab shakes

- docs/tag/demo/selectable.md
- package.json
- src/tag/selectable.jsx
- test/tag/index-spec.js
- derive checked state from props
> fix(Tag): fix state not matching props

- src/menu/view/menu.jsx
- src/util/object.js
- test/util/object-spec.js
A `in` expression was used in previous conditional branches, that
expected to determine whether a specific props has been declared
at the component.
e.g.:
```javascript
class MyComponent extends Component {
componentDidMount() {
// print `foo` if `this.props.foo` is not declared
if (!('foo' in this.props)) {
console.log('bar')
}
}
render() {
return (
<div>{this.props.foo}</div>
)
}
}
```
In most cases, there has no problems if the prop `foo` is not
declared:
```javascript
// `foo` is not declared,
// and it will print `bar` when component did mount.
<MyComponent />
```
But it still has problems in some specific edge cases:
```javascript
// `foo` is declared as an undefined value,
// and `foo` is in the component's props.
// `bar` will not be printed.
<MyComponent foo={undefined} />
// …
```
> fix(Menu): Resolve expanding and selecting in uncontrolled mode

- src/tab/tabs/nav.jsx
Remove extra from the listened area of keydown event.
Closing #643
> fix(Tab): should not listen to extra keyboard events

- docs/field/demo/topath-defaults.md
- src/field/index.js
- test/field/index-spec.js
- test/field/options-spec.js
- test/field/rules-spec.js
- field constructor saves passed values
- field init looks at constructor values for defaults
> fix(Field): parseName defaults

- types/date-picker/index.d.ts
声明文件中onOk是一个没有参数的函数
``` javascript
onOk?: () => Array<any>;
```
实际上应该和onChange一样，传入一个带参数的
``` javascript
onChange?: (value: Array<any>) => void;
```
> fix(Date-picker): prop 'onOk' typescript declaration File wrong

- src/checkbox/main.scss
- src/checkbox/scss/variable.scss
- src/radio/main.scss
Checkbox需要分离变量(会单独提交).
Radio不需要,之前已经有相关的sass变量,但是只用在了Group为disable的情形下,radio单独用的时候没有考虑,本次改动支持了单独使用Radio的情形.
> Checkbox & Radio Add Config

- src/number-picker/index.jsx
- test/number-picker/index-spec.js
support null to reset NumberPicker
> Fix(NumberPicker): set null to reset value

- src/core/style/_font.scss
添加font weight变量，在原来的基础上添加4个变量，在配置平台使用，用来让用户在组件中选择修改字重，定义字重：https://fusion.design/design/style/font
> feat(Theme): add font weight

- src/field/index.js
- test/field/index-spec.js
- set `values` cache when controlled component with `init` props
> fix(Field): fixes #880

- src/upload/runtime/uploader.js
修复beforeUpload return false 或者 Promise.reject() 时候 不显示 errorcode的问题
beforeUpload returns false or  Promise.reject() , errorcode could not be get in OnError method
> fix(Upload): errorcode in beforeUpload

- types/upload/index.d.ts
Closes https://github.com/alibaba-fusion/next/issues/936
DraggerProps 直接继承 UploadProps 即可。
> chore(Upload): correct TypeScript Upload Dragger props

- src/tree-select/tree-select.jsx
- src/tree/view/tree.jsx
- src/tree/view/util.js
- test/tree-select/index-spec.js
- test/tree/index-spec.js
fixed https://github.com/alibaba-fusion/next/issues/872
> fix(Tree): Still can check after disableChecked

- src/tab/tabs/nav.jsx
fix #959 by removing focus logic in didUpdate hook.
> fix(Tab): only focus active tab after first render

- package.json
- scripts/build/export-api-schema.js
- src/balloon/inner.jsx
- src/dialog/inner.jsx
- src/drawer/inner.jsx
- src/message/message.jsx
- src/table/base/sort.jsx
- src/table/list/row.jsx
- tsconfig.json
- types/config-provider/index.d.ts
- types/locale/default.d.ts
- types/locale/en-us.d.ts
- types/locale/ja-jp.d.ts
- types/locale/zh-cn.d.ts
- types/locale/zh-tw.d.ts
close #995 
close https://github.com/alibaba/ice/issues/2667
> Add d.ts. for locale & prevent some warning

- src/dialog/show.jsx
- test/dialog/index-spec.js
修改后， 快捷调用时，设置 prefix ，会同时对 dialog 生效。
> fix(Dialog): quick-calling support set prefix to dialog

- src/notification/index.jsx
现在Notification的title和content都是必填，否则出不来，应该是任选其一展示就可以
> fix(Notification): title and content are not both required

- types/notification/index.d.ts
Fixed type error related to alibaba-fusion#1322
Notification.success(config)
Notification.error(config)
Notification.warning(config)
Notification.notice(config)
Notification.help(config)
Notification.open(config)
Notification.close(key: String)
Notification.destroy()
> Fixed(Notification): type define error

- src/table/fixed.jsx
- src/table/lock.jsx
修复了  在插着鼠标的时候 fixedHeader  lock 模式下，table header 高度不一致问题
> fix(Table): disorder with mouse

- src/upload/runtime/request.jsx
- src/upload/runtime/selecter.jsx
修复 Upload 组件在 IE 浏览器（IE11）下的兼容性问题：
- 在 IE 浏览器下，`timeout` 属性必须设置在  `xhr.open` 之后 `xhr.send()` 之前
- 手动触发 `input[type=file]` 的 `click` 事件之后又设置 `el.value = ""`，会触发 `input[type=file]` 两次 `onChange` 事件
> fix(Upload): bugs of IE

- docs/input/theme/index.jsx
配置Input正常状态下的背景色，配置面板总是不出来
如果点到了Input 触发了focus，那么就成了配置focus的面板，所以点击需要点到白色的地方，不能点到输入框上
禁用normal状态下的Input点击
> docs(Input): can not see normal background

- types/config-provider/index.d.ts
config function second params is not required in ts
> fix(ConfigProvider): second params is not required in ts

- src/nav/main.scss
单独配置subnav的高度时会上下不居中，修复 https://github.com/alibaba-fusion/next/pull/1735
> fix(Nav): fix sub nav vertical not middle

- src/nav/main.scss
当item高度很高的时候，箭头在展开、未展开的情况下位置偏移明显
> Fix nav style

- docs/icon/index.en-us.md
- docs/icon/index.md
- src/icon/icon-font.jsx
- src/icon/main.scss
- types/date-picker/index.d.ts
- types/icon/index.d.ts
加载外部iconfont源的方法的cache，是在next.js中记录了一个变量，来存储历史缓存过的scriptUrl，但是在ice-stark的模式下，不同子应用之前使用的不是同一份next.js 所以cache在这种情况下是无效的。
添加id，根据id来判断是不是全页面唯一
> fix(Icon): add id for custom icon

- src/responsive-grid/create-style.js
- test/box/index-spec.js
When wrap and spacing setted, the outer `next-box 1` will not have the style `justify-content:center` since it is filtered by using `innerProps` which is meant to be kept for inner `next-box 2`. Meanwhile, as the "between" div doesn't set its width, the inner `next-box 2` can not calculate its x axis width, so its `justify-content` won't work.
```html
<div class="next-box 1" style="padding: 20px;">
<div class="between" style="margin: -0.5px; overflow: hidden;">
<div class="next-box 2" style="flex-flow: row wrap;justify-content: center;">
<div class="next-box box-180-50" style="flex-flow: column nowrap; margin: 0.5px;"></div>
<div class="next-box box-180-50" style="flex-flow: column nowrap; margin: 0.5px;"></div>
<div class="next-box box-180-50" style="flex-flow: column nowrap; margin: …
```
> fix(Box): resolve justify wont work when wrap&spacing setted, close#1855

- src/date-picker/date-picker.jsx
- src/date-picker/range-picker.jsx
- test/date-picker/index-spec.js
- 当开始和结束选同一个日期的时候，会导致结束时间被清空，开始时间置0
- 手动修改日期的时候，也会导致时间被置0
修复：
修改日期时，如果起始时间和结束时间是合理的，不会重置时间
> fix(DatePicker): should not resetTime as default,close #1840

- src/breadcrumb/scss/mixin.scss
> fix(Breadcrumb): separator icon's vertical align should be middle

- src/search/main.scss
- src/search/rtl.scss
sass编译的时候，百分值和长度值进行运算的时候需要使用calc方法，或者会报错
> fix(Search): fix Incompatible units on sass compile

- src/overlay/gateway.jsx
版本低于16.3的React，forceUpdate方式并不触发get­Derived­State­From­Props事件，会导致containerNode没法更新到
> fix(GateWay): getDerivedStateFromProps don`t execute

- src/tab/scss/mixin.scss
fix #2061 
缩小关闭叉号icon点击的热区
将文案和叉号icon之间的空白 从padding换成margin
为padding时，点击空白处也会将tab关闭，在切换tab的时候十分容易造成误点，给用户造成困惑。
改成margin后，样式不变，点击空白处不会关闭tab。
> fix(Tab): narrow close icon hot area

- src/badge/sup.jsx
因为种种奇怪的原因（比如浏览器缩放），浏览器`window.getComputedStyle(supNode).height`返回的可能不是一个整数，比如我们期望返回`18px`然而它返回`17.997px`：
parseInt以后会变成17，原本很小的精度丢失被放大，导致badge的滚动位置计算出现较大误差：
> fix(Badge): fix count scroll position

- types/number-picker/index.d.ts
number picker的ts中，props的interface缺少了alwaysShowTrigger的字段
> fix(NumberPicker): add alwaysShowTrigger in types/number-picker

- src/switch/index.jsx
- test/switch/index-spec.js
preview 模式下，如果没设置 renderPreview，优先使用 checkedChildren / unCheckedChildren
> feat(Switch): 修改 preview 模式下展示内容

- docs/field/index.md
- src/select/main.scss
ie 下 readonly 的 input 会带有 输入标识，目前暂时无法解决。
用 unselectable 会去除光标，但是 placeholder 也会丢失。对比起来觉得还是 placeholder 更重要。
> fix(Select): placeholder in ie11

- src/input/group.jsx
- src/input/input.jsx
- src/menu/view/menu.jsx
- src/search/Search.jsx
我们这边对于可选择的menu（即带有✔️符号的menu），需要做一些样式覆盖，但是目前没有可靠选择器能够选中”可选择的menu“。
> feat(Menu): add selectable classnames

- src/form/form.jsx
- src/responsive-grid/create-style.js
- src/responsive-grid/index.jsx
- src/responsive-grid/main.scss
- types/form/index.d.ts
ResponsiveGrid 不支持IE
ResponsiveGrid采用css grid能力实现，由于IE11浏览器的Grid解析内核与现代浏览器不同，一些需要大量浏览器绘制计算的能力IE11不具备，例如：
- 自动布局能力：现代浏览器下，给css grid的children 设置占据几行几列，他们会自动在剩余空间进行排布。而在IE11下虽然有类似的占据几行几列的API，但是它没有自动在剩余空间进行排布的能力，用户只能给不同位置的child设置不同的行列的起始位置，这一功能需要大量计算，也就是说如果组件想要兼容IE11，就相当于把现代浏览器的排布能力在组件层面实现了一遍。
- 元素间的间距gap：IE11没有类似API，不支持设置子元素间的gap
- 其他相对来说不方便，但是有解决方案的点，例如repeat(1fr, 4) 可以写成 1fr 1fr 1fr 1fr
上述问题中，前两个比较严重，只通过简单的autoprefixer没办法兼容IE11。   参考 https://stackoverflow.com/questions/45786788/css-grid-layout-not-working-in-ie11-even-with-prefixes
从原因上可以看出，继续在IE的css-grid环境下进行各种优化走不通。综合考虑之后准备通过Flex布局 + margin来实现类似的功能，语义逻辑上比较奇怪，但是能力基本匹配，具体方案见本PR。
大概率上没有问题，但是可能会有不可预期的样式问题，例如通过Flex在实现gap的时候，用到了3层元素来hack，设置了overflow hidden，所以followTrigger的弹窗可能会有问题
> feat(ResponsiveGrid): support ie11 for css grid

- src/search/index.jsx
```jsx
// src/search/index.jsx
export default ConfigProvider.config(Search, {
transfrom: (props, deprecated) => {
const { onInputFocus, overlayVisible, combox, ...others } = this.props; // this use as gloablThis
}
});
```
ESM bundle:
The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten.
This PR fixes the above warning.
> fix(Search): correct usage of this and avoid warning for esm bundle

- src/number-picker/number-picker.jsx
- test/number-picker/index-spec.js
修复以下问题：
1. 设置小数点后输入位数不可超过precision，否则截断，未设置则precision=0。修复小数点后0可以无限输入的问题，解决小数点后0输入过长后键入非0数字会转科学计数法的问题；
2. 不允许输入多于一个.或-字符，若粘贴字符串中有多于一个，则从第二个处截断。
> fix(NumberPicker): fix unexpected scientific notation display,close#2243

- src/number-picker/main.scss
number-picker 中按钮控制（extra元素）中 .next-input-control未设置height，
chrome中会以父元素高度为基准自动计算，而firefox中则不会，
导致firefox中子元素.next-number-picker-handler的height: 100%的高度计算出错，未撑满整个NumberPicker
> fix(NumberPicker): fix trigger height problem in firefox, close#2281

- src/select/select.jsx
google translate 翻译的时候会把文字转为 font 标签，dom 结构变化 unmount 的时候找不到元素导致页面 crash
可以在文字上面包裹 span 避免此 bug
<span aria-hidden>{mirrorText || placeholder}&nbsp;</span>
translate 后 变成
image
文字包裹下 span 可解，不要出现一半文字一半span
详细见 issue #2424
> fix(Select): google translate bug fix #2424

- src/core/util/_function.scss
- src/nav/scss/mixin.scss
增强鲁棒性，支持低版本的主题包变量，搭配高版本的样式体。
背景：
低版本的主题包中，会出现值为`0`的变量（没有单位），而这种变量用到`calc`中会报错，例如`calc(4px - 0 )`是不合法的。虽然高版本的样式变量不会返回`0`这种不合法值，但是老的主题包没办法避免，所以修改高版本的样式体，增强鲁棒性
> chore(*): enhance robotness

- src/core/util/_function.scss
- src/nav/rtl.scss
- src/nav/scss/mixin.scss
https://github.com/alibaba-fusion/next/pull/2444 这个版本的修改虽然可以解决sass用户的问题，但是对于css var用户来说，增加的sass函数无法被解释，所以仍然有问题。
最终采用fallback样式的办法来解决，因为只有在值为 `0` 时才会遇到这些问题，所以把值为 `0` 默认写进去
> chore(*): enhance robotness for css var

- src/input/main.scss
- src/input/scss/variable.scss
为了支持精致度升级，以及DatePicker2的加入，所有Input都应该设置下focus时的高亮状态，例如：
因此把基础组件的默认样式改掉，影响的范围是：没有设置过主题包的用户。
对于所有设置过主题包的用户而言，他们的样式数据存储在主题包里，甚至不用拆分变量，完美！
> Feat: add focus state for Input

- src/number-picker/index.jsx
- src/number-picker/number-picker.jsx
> feat(NumberPicker): support ref.getInputNode

- src/cascader/cascader.jsx
close #2518
代码 commit 时自动执行了 pre-commit 的 lint 和 prettier 的钩子，导致文件看起来变更很多。实际只有下面的计算宽度的变更
```diff
const menusWidth = Math.ceil(
menus.reduce((ret, menu) => {
-                return ret + getStyle(menu, 'width');
+                return ret + Math.ceil(menu.getBoundingClientRect().width);
}, 0)
);
```
> fix(Cascader): fix cascader width

- scripts/preview/loaders/index/render-creator.js
黄金令箭方案改为从demo页发送点击/编辑事件message给站点，站点接收后进行埋点信息发送
> chore(*): move goldlog send to site

- src/form/item.jsx
- types/form/index.d.ts
目前Form.Item上面写的valueName，因为没有在propTypes上面定义，会被应用到DOM上，导致react报错。
已本地验证，在propTypes上加上即可修复。
> fix(Form): add valueName

- src/step/view/step-item.jsx
- src/step/view/step.jsx
修复 Step stretch 属性透传到 dom warning
> fix(Step): stretch props warning

- docs/box/demo/align&justify.md
- docs/box/demo/padding&margin.md
- docs/dialog/demo/large-content.md
- docs/dialog/demo/withContext.md
md解析库默认会将title中&进行转义，避免demo展示转义后的符号，删除之。
> docs(*): remove & in md title

- docs/switch/demo/checked-children.md
- docs/switch/demo/loading.md
- docs/switch/theme/index.jsx
- src/switch/index.jsx
- src/switch/main.scss
- src/switch/rtl.scss
- src/switch/scss/mixin.scss
- src/switch/scss/variable.scss
- src/switch/style.js
可能的变化：
1. switch由原来的固定宽（width: $s-4）,改为min-witdh，最小宽
2. switch现在宽度随着内容变化，内容长switch就长
> feat(Switch): add loading & style refactor

- docs/breadcrumb/demo/custom-item.md
- docs/breadcrumb/demo/separator.md
- docs/breadcrumb/demo/show-hidden-more.md
- docs/breadcrumb/index.md
- src/breadcrumb/index.jsx
- src/breadcrumb/main.scss
- src/breadcrumb/scss/mixin.scss
- src/breadcrumb/style.js
- test/breadcrumb/index-spec.js
- types/breadcrumb/index.d.ts
https://github.com/alibaba-fusion/next/issues/2968
- 增加`showHiddenItems`属性表示*点击省略号是否展示被隐藏的项*，默认`false`（版本兼容性）。
- 如设置`showHiddenItems: true`，则省略号的css class变更为`next-breadcrumb-text-ellipsis-clickable`。
- `Breadcrumb`组件增加对`Dropdown`和`Menu`的依赖。
- 增加相关demo。
> feat(Breadcrumb): add `showHiddenItems` prop

- src/config-provider/index.jsx
被esbuild打包的时候，`require('moment')`得到的是模块对象，它的default才是我们需要的moment对象。
> fix(ConfigProvider): fix moment import

- src/select/util.js
useDetailValue 的时候 object 对象里面并没有value 的兼容性判断！
> fix(Select): should support object without value in item

- docs/table/demo/list.md
- src/table/virtual.jsx
- test/table/index-spec.js
https://github.com/alibaba-fusion/next/commit/e2aaf44 这个commit引起的，原来判断只会有didmount时的一次，后面改到了每次更新都查看。在后续更新的时候可能存在bodyNode不存在的情况（比如ListTable没有bodynode，所以ListTable一直没有虚拟滚动的能力，这里增强处理先避免报错）
> fix(Table): bug when list table with useVirtal

- src/table/base/cell.jsx
- src/util/index.js
- src/util/pick-attrs.js
之前 Table `columns` 中的配置项会将所有属性透传，会出现 warning，现在将这些属性过滤掉。
> fix(Table): 过滤掉无效的透传到dom属性

- src/tree-select/tree-select.jsx
移动tree-select一些props到others后面，防止被外界错误覆盖。
例如目前版本中，如果外界使用：
```
<TreeSelect mode={undefined} />
```
因为others在后面，会导致传到Select上面的mode属性被替代，显示不正常。
Demo：（该Demo在选择选项后，下拉框中没有显示选项）
https://riddle.alibaba-inc.com/riddles/cd2caba6
对比图：
不正常
正常
> fix: move some props to behind others

- src/date-picker2/main.scss
> fix(DatePicker2): use flex-basis instead width to be compiable with safari, close #3463

- src/core/style/_size.scss
sass support syntaxes of comments in two ways:
- comments defined using /* */ that are (usually) compiled to CSS
- comments defined using // that are not
it will be nice to use // syntaxes while it do not compiled to CSS, it may cause some strange behavior while compile css in postcss
> fix: using // sass comments in scss

- src/core/form-element.scss
- src/core/utility/_form-element.scss
这里写样式只是为了配置的时候能够读取到变量，必须 next-form-element 开头的样式才能被读到
以下样式对组件没有作用
> fix(Form): theme config for preview label font-size

- src/core/util/_function.scss
fix issue #3716 
目前测试的情况：
* npm run check-sass: 都不告警，原来的话 dart-sass 会告警
* npm run build（使用 node-sass 构建）: check icon.css 结果正常
* npm run pack（使用 dart-sass 构建）：check next.css 结果正常，且不告警，原来的话会告警
> fix(Core): division deprecation warning when using dart-sass

- src/input/password.jsx
当密码输入框为disabled状态时, 
用户点击后面眼睛icon依然可以触发显示明文的逻辑，实际上不应该触发。
> fix(Input): 修复密码输入框在禁用态的时候仍然可以点击右侧的眼睛来切换显隐的问题

- src/upload/card.jsx
在某些场景下，从只读态切换到输入态时，点击删除，会因为 List 的 props.uploader 不存在导致删除动作不触发。
> fix(upload): 修复从只读态切换到输入态时无法删除已上传的问题

- src/dialog/dialog.jsx
- types/dialog/index.d.ts
> fix(types): dialog height can be number

- src/tree-select/tree-select.jsx
- test/time-picker2/index-spec.js
> fix(TreeSelect): calculate all checked value only when treeCheckedStrategy=all, close#3936

- types/slider/index.d.ts
TypeScript 类型中缺少了 pauseOnHover 属性
> fix(types/slider): pauseOnHover prop

- package.json
- src/number-picker/number-picker.jsx
- test/number-picker/index-spec.js
big.js 大约比 bignumber.js 小一半体积，能节约几个 KB。功能上完全能够满足 fusion 组件内的需要。
> refactor: use big.js instead of bignumber.js, for smaller bundle size

- src/table/base-pre.jsx
- src/table/base.jsx
- src/table/main.scss
loading 后不再有层级变化，所以 ref 也不会再重新计算。
> fix(Table): loading crash fix #3369

- docs/icon/demo/type.md
解决icon的预览页中，icon的font_class值超长导致的样式错乱
> fix(IconDocs): icon文档font_class超长省略显示

- types/table/index.d.ts
expandedRowIndent 应该是固定两位数字，不能多也不能少。之前的 TypeScript 类型定义并没有限定数组长度。
> fix(Table): expandedRowIndent 类型限制

- src/core/style/_corner.scss
A size value without unit maybe cause 'invalid property value' warnings in `calc()` css function, meanwhile this stylesheet cannot style correctly. Example below:
add a unit to make it more reusable ^_^.
> fix: make one scss variable more reusable

- src/upload/upload.jsx
- test/upload/index-spec.js
修复Upload在同时设置listType=card以及isPreview=true两个属性的时候，onPreview回调函数不触发的问题
> fix(Upload): resolve onPreview method fails in preview mode, close #3830

- src/card/main.scss
在一些场景中，卡片内嵌套卡片，最外层的 next-card-show-divider 类会影响内部卡片，导致内嵌卡片无法隐藏 divider。
此 PR 限制 css selector 只对当前 card 组件生效，不影响嵌套的 card。
一个例子 https://o2.alibaba-inc.com/sandbox/ide?id=267
> fix(Card): limit show/hide divider selector

- src/form/item.jsx
- test/form/validate-spec.js
The useLabelForErrorMessage of FormItem should have a higher priority.
> fix(Form.Item): priority of properties

- src/config-provider/config.jsx
问题：使用通过ConfigProvider.config包裹的hooks组件时，没有办法通过ref获取到该组件的实例
解决方案：ClassComponent和hooksComponent的ref相同处理即可
> fix(ConfigProvider): support using ref on function component, close #4203

- src/menu/view/menu.jsx
这样的改动在试了几个方案后改动最小，被折叠的 item 主要用途是计算宽度，不需要拿真实的 key导致计算时 p2n 和 k2n 被重复计算，且位置错误。
> fix(Menu): fix hozInLine mode popup bug when subMenu has a specified key, close #4222

- src/balloon/balloon.jsx
> fix(Balloon): the offset attribute does not take effect after the v2 version is enabled

- src/dialog/show.jsx
ConfigProvider.config默认会传递ref，这里的dialog2组件没有设置forwardRef，故而development模式下的react会报告一个warning。这个场景下，dialog2组件是不需要开放ref的，所以仅仅做一层forwardRef包裹。
> fix(Dialog2): clear warning by ConfigProvider cross ref props with no forwardRef component, close #4246

- types/checkbox/index.d.ts
导出checkBox的dataSource的子项类型，如果某个组件封装了一层checkBox，可能需要这个类型
> chore(checkbox): export dataSource item type

- components/input/index.d.ts
- types/input/index.d.ts
Fixed an issue where the `composition` attribute was missing from the type definition of the Input component.
> fix(Input): Fix the type definition issue of Input component

- components/box/index.d.ts
- types/box/index.d.ts
Fixed an issue where the `component` attribute was missing from the type definition of the Box component.
> fix(Box): Fix the type definition issue of Box component

- components/date-picker2/__docs__/demo/format/index.tsx
- components/date-picker2/__tests__/index-spec.js
- components/locale/en-us.ts
- components/locale/types.ts
修复DatePicker2英文翻译不符合国际化规范，新增format示例：英文翻译后更符合国际化规范
close #4788
> fix(DatePicker2): Translation compliant with international standards

- components/message/__tests__/issue-spec.tsx
- components/message/scss/mixin.scss
> fix(Message): The styles of the outer Message component will affect the inner component when nested, close #4851

- components/date-picker2/__tests__/index-spec.js
- components/date-picker2/picker.jsx
> fix(DatePicker2): check disabledDate after clicking ok, close #3801

- components/date-picker2/__tests__/index-spec.js
- components/date-picker2/picker.jsx
> fix(DatePicker2): Unable to enter space to enter time

- components/select/__tests__/issue-spec.tsx
- components/select/select.tsx
- components/select/types.ts
fix(Select): should be able to select multiple options in multi-select, close #3590
> fix(Select): should be able to not clear search value in multiple mode, close #3590

- components/tree/__docs__/demo/search-tree/index.md
- components/tree/__docs__/demo/search-tree/index.tsx
- components/tree/__tests__/index-spec.tsx
- components/tree/view/tree.tsx
> feat(Tree): The Tree component provides the scrollFilterNodeIntoView API, which scrolls the first matched node of a search into view

- components/select/__tests__/issue-spec.tsx
- components/select/select.tsx
fix(Select): disabled does not affect all selections close #4802
> fix(Select): Selecting all does not affect options that are already disabled 4802

- components/virtual-list/__tests__/index-spec.tsx
- components/virtual-list/virtual-list.tsx
Children.toArray will change the key of child, see https://react.dev/reference/react/Children#children-toarray for details
close #4942
> fix(VirtualList): stabilize children keys in virtual list

- components/grid/__tests__/index-spec.tsx
- components/grid/col.tsx
- components/grid/row.tsx
- components/grid/types.ts
https://github.com/orgs/alibaba-fusion/projects/1/views/1?pane=issue&itemId=78371885
> The style prop of Col in the Grid does not take effect

- components/date-picker2/__tests__/index-spec.js
- components/date-picker2/picker.jsx
https://github.com/orgs/alibaba-fusion/projects/1?pane=issue&itemId=72533164
> fix(DatePicker2): after entering a customized date format and pressing Enter, the value should not change,closed alibaba-fusion#4896

- components/balloon/__tests__/balloon-v2-spec.tsx
- components/balloon/balloon.tsx
> fix(Balloon): v2 default offset adjustment

- components/core/util/_varMap.scss
如题，构建工具使用sass-loader 配置 additionalData 引入主题包内的 variables.scss2css.scss 文件进行编译时， 该文件的 varMap 赋值会被scss 文件内的顶部的 @import "..../core/util/_varMap" 覆盖，导致编译异常。
错误提示大致如下：
> fix(Core): 修复使用 css variable 模式构建时，主题包内的 varMap 配置值会被重复覆盖的问题

- components/time-picker2/__tests__/index-spec.tsx
- components/time-picker2/index.tsx
TimePicker2 在透出的时候 assignSubComponent 方法没有用ConfigProvider包裹的TimePicker2，导致ConfigProvider 设置 locale时，TimePicker2不生效
> fix(TimePicker2):  support set locale by ConfigProvider
