- scripts/utils/check-name.js
- src/nav/main.scss
- src/nav/scss/mixin.scss
- src/nav/scss/variable.scss
> fix(Nav): primary/secondary active border

- src/input/main.scss
> fix(Input): input border-radius with one addonText

- docs/upload/theme/index.jsx
- src/input/scss/variable.scss
- src/search/main.scss
- src/search/scss/mixin.scss
- src/search/scss/variable.scss
1. Fix Search/Input ConfigPlatform Bug
2. Fix Upload ConfigPlatform visual bug
> Fix Search/Input/Upload bugs

- docs/config-provider/index.en-us.md
- docs/config-provider/index.md
- site/en-us/font-deploy.md
- site/en-us/theme.md
- site/zh-cn/font-deploy.md
- site/zh-cn/theme.md
> mod theme doc

- site/zh-cn/i18n.md
> docs(*): mod i18n doc

- docs/checkbox/index.en-us.md
- docs/field/demo/dynamic.md
- docs/field/demo/mix.md
- docs/field/demo/onchange.md
- docs/field/demo/validator.md
- docs/field/index.en-us.md
- docs/field/index.md
- src/checkbox/checkbox.jsx
> Review checkbox field

- src/form/item.jsx
- test/form/index-spec.js
use like 
```
<Item>
{
(values) => {
return values.name === 'frank' <p>frank exisetd</p>: <Input />
}
}
</Item>
```
> feat(Form): Item support function children

- src/tab/main.scss
- src/tab/scss/variable.scss
1. make bg-color configurable in pure mode
2. remove divider-style from configurable items
> fix(Tab): Make bg-color configurable

- src/upload/upload.jsx
feat(Upload): shallow copy value
> feat(Upload): shallow copy value

- docs/checkbox/index.md
- docs/radio/index.md
- scripts/server/middlewares/rebuild-scss.js
- src/checkbox/checkbox.jsx
- src/radio/radio.jsx
- src/range/scss/mixin.scss
- src/range/view/range.jsx
- src/tab/main.scss
Currently when label is number it won't work, so change type check as well as document.
> fix(Checkbox,Range,Tab): a bunch of issues

- docs/dialog/demo/quick.md
- src/config-provider/cache.js
- src/config-provider/index.jsx
- test/dialog/index-spec.js
- test/message/index-spec.js
> fix(ConfigProvider): Isolate multiple context data

- src/upload/main.scss
style(Upload): add drag box padding
> style(Upload): add drag box padding

- src/table/virtual.jsx
Reverts alibaba-fusion/next#98
> Revert "fix(Table): can't find unmounted component"

- docs/tab/index.en-us.md
- docs/tab/index.md
- src/grid/row.jsx
Fix inconsistency between document/comment and code.
Tab: disabled
Grid: default value of align and justify
> fix(Tab, Grid): inconsistency between doc and code

- src/switch/main.scss
- src/switch/scss/variable.scss
> fix(Switch): tweak switch off-state right padding

- src/progress/view/progress-circle.jsx
- src/progress/view/progress-line.jsx
progressbar accessibility support
> progressbar accessibility support

- src/search/main.scss
> style(Search): fix select height in Search

- src/select/select.jsx
Reverts alibaba-fusion/next#144
> Revert "fix(Select): Option value can be array"

- src/dialog/show.jsx
- test/dialog/index-spec.js
> feat(Dialog): throw Error when occur in onOk

- docs/collapse/demo/accessibility.md
- src/collapse/collapse.jsx
- src/collapse/panel.jsx
- test/collapse/index-spec.js
collapse accessibility support
> collapse accessibility support 

- docs/form/index.md
- src/field/utils.js
- src/form/item.jsx
- src/form/main.scss
- src/select/select.jsx
1. switch align in size=large
2. warning while  use like `message={<span>xx</span>}`
> switch align in Form size=large, remove warning while message={<span/>}

- src/radio/main.scss
> fix(Radio): button shape hover border covers checked border

- docs/loading/demo/fullscreen.md
- add button as safe node to disable document event handler
> fix(Loading): fix fullscreen in demo

- src/tab/main.scss
- src/tab/rtl.scss
- src/tab/tab.jsx
- src/tab/tabs/nav.jsx
https://github.com/alibaba/ice/pull/1318
> fix(Tab): extra align middle by default

- src/nav/main.scss
https://github.com/alibaba/ice/pull/1318
> fix(Nav): overflow when icon-only without icon

- docs/upload/demo/image.md
- docs/upload/demo/text.md
- docs/upload/index.en-us.md
- docs/upload/index.md
- docs/upload/theme/index.jsx
- src/upload/card.jsx
- src/upload/list.jsx
- src/upload/main.scss
- src/upload/scss/variable.scss
- src/upload/upload.jsx
- test/upload/image-spec.js
- test/upload/text-spec.js
Feat(Upload): upload text list error msg
> Feat(Upload): upload list error msg

- src/upload/main.scss
- src/upload/scss/variable.scss
temp(Upload): add icon color configable
> temp(Upload): add icon color configable

- docs/tab/demo/basic.md
- docs/tab/demo/disabled.md
- src/tab/main.scss
- src/tab/tabs/nav.jsx
Tab a11y feature, also fixes #145
> feat(Tab): tab a11y

- src/range/view/range.jsx
- src/range/view/slider.jsx
- test/range/index-spec.js
It's only supporting single slider now, this PR didn't include double slider solution, and honestly I haven't though out a solution for it yet.
> feat(Range): a11y

- test/collapse/a11y-spec.js
- test/util/a11y.js
title is required for panel titles
also stringified the axe violations to help debugging
> test(Collapse): fix missing title for panel a11y test

- src/checkbox/checkbox.jsx
- test/checkbox/group-spec.js
> fix(Checkbox): group didn't honor children's indeternimated state

- src/table/selection.jsx
- useVirtual
- check one and scroll untill it's out of visual area
close #246
> fix(Table): head selection emptied wrongly

- scripts/webpack/prod.js
> chore(*): add banner for files in dist

- src/dialog/inner.jsx
- src/locale/en-us.js
- src/locale/ja-jp.js
- src/locale/zh-cn.js
- src/locale/zh-tw.js
- src/tag/tag.jsx
- test/collapse/a11y-spec.js
- test/dialog/a11y-spec.js
- test/loading/a11y-spec.js
- test/overlay/a11y-spec.js
- test/overlay/index-spec.js
- test/progress/a11y-spec.js
- test/tag/a11y-spec.js
- test/tag/index-spec.js
- test/util/a11y/validate.js
updates for a11y and a11y unit tests these components
> test(*): a11y updates: dialog, tag, collapse, loading, overlay, progress

- test/badge/a11y-spec.js
- test/balloon/a11y-spec.js
- test/breadcrumb/a11y-spec.js
- test/button/a11y-spec.js
- test/card/a11y-spec.js
- test/dropdown/a11y-spec.js
- test/icon/a11y-spec.js
- test/menu-button/a11y-spec.js
- test/menu/a11y-spec.js
- test/message/a11y-spec.js
- test/paragraph/a11y-spec.js
- test/radio/a11y-spec.js
- test/util/a11y/validate.js
some are skipped to help the maintainer focus on the fix and not the unit test code
> More unit tests for components

- docs/upload/demo/beforeupload.md
> docs(Upload): mod upload doc

- src/table/expanded.jsx
- src/table/expanded/row.jsx
- test/table/index-spec.js
Reverts alibaba-fusion/next#317
> Revert "fix(Table): correct index in expandedRowRender and getExpandedColProps"

- README.md
- docs/form/index.md
- docs/upload/index.md
- docs/virtual-list/index.md
- src/upload/upload.jsx
增加组件设计思路到 readme
- Form 表单组件的设计之路 https://zhuanlan.zhihu.com/p/56280821
- virtual-list https://zhuanlan.zhihu.com/p/55329238
- Upload 上传组件设计思路 https://zhuanlan.zhihu.com/p/56684600
> docs(*): update readme for link about component design

- src/menu/rtl.scss
- src/slider/slick/track.jsx
- https://github.com/alibaba-fusion/next/blob/573694ac33c95adfc8427e12cb20dd71273eb75e/src/menu/main.scss#L158
> fix(*): style for rtl in Menu & Slider

- src/paragraph/index.jsx
- test/paragraph/index-spec.js
> feat(Paragraph): add rtl prop

- src/rating/main.scss
- src/rating/rating.jsx
- src/rating/rtl.scss
- test/rating/index-spec.js
> feat(Rating): support rtl

- src/affix/index.jsx
- test/affix/index-spec.js
receive the change of offset props;
close #203 .
> feat(Affix): receive the change of offset props

- src/card/card.jsx
- src/card/main.scss
- src/card/rtl.scss
- src/card/scss/rtl.scss
> feat(Card): move rtl.scss

- docs/rating/demo/grade.md
- docs/rating/index.en-us.md
- docs/rating/index.md
- src/rating/rating.jsx
Support custom display of rating grade;
close #273 .
> feat(Rating): support custom display of rating grade

- docs/table/demo/expanded-complex.md
- src/table/base.jsx
- src/table/base/body.jsx
- src/table/base/cell.jsx
- src/table/base/row.jsx
- src/table/expanded.jsx
- src/table/expanded/row.jsx
- test/table/index-spec.js
- the step changed from 2 to 1
https://github.com/alibaba-fusion/next/pull/317
可能会引起breakchange
> fix(Table): correct index in expandedRowRender and getExpandedColProps

- src/transfer/view/transfer.jsx
- test/transfer/index-spec.js
> feat(Transfer): support rtl prop

- src/switch/index.jsx
- src/switch/main.scss
- src/switch/rtl.scss
- src/switch/scss/variable.scss
It looks changes many, but if you sync feat/rtl2 with master firstly and then review this MR, it would be ok as I rebased my feature branch with master.
> [ Switch] RTL feature

- src/tab/tabs/nav.jsx
- test/tab/index-spec.js
> fix(Tab): a11y support closeable tab

- src/search/Search.jsx
chore(Search): fix aria spell mistake
> chore(Search): fix aria spell mistake

- src/date-picker/module/panel-footer.jsx
- src/date-picker/range-picker.jsx
fixed https://github.com/alibaba-fusion/next/issues/388
> fix(DatePicker): date range picker select time error

- .gitignore
- src/tab/tabs/nav.jsx
- test/tab/index-spec.js
Fixes #226 
The basic idea is only auto scroll to active tab when the item mount, not auto scroll when the component re-renders
> fix(Tab): can't scroll when active item is inside view

- docs/grid/index.en-us.md
- docs/grid/index.md
- src/radio/radio-group.jsx
- src/tab/tabs/nav.jsx
- test/checkbox/a11y-spec.js
- test/grid/a11y-spec.js
- test/radio/a11y-spec.js
- test/range/a11y-spec.js
- test/switch/a11y-spec.js
- test/tab/a11y-spec.js
- Add accessibility tests for Tab, Range, Switch, Radio, Checkbox, Grid
- Fix some accessibility issues found during the tests
- Add a11y related documentation for Grid
> test(*): add a11y tests and some a11y fix

- src/step/view/step-item.jsx
- test/step/index-spec.js
> fix(Step): step-item param of labelPlacement change update bug

- src/step/view/step-item.jsx
- test/step/index-spec.js
> fix(Step): labelPlacement value change dbl times

- docs/select/demo/multiple.md
- src/select/base.jsx
- src/select/main.scss
- src/select/select.jsx
- test/select/index-spec.js
related to https://github.com/alibaba-fusion/next/issues/287
> feat(Select): can unselect all

- .travis.yml
- package.json
- scripts/test/a11y-allinone.js
- scripts/test/a11y-index.js
- scripts/test/allinone.js
- scripts/test/index.js
- scripts/test/karma.js
- test/util/a11y/validate.js
- allow running a11y unit tests alone
- don't run a11y unit tests with all other unit tests
- fix issue with a11y/validate where it wasn't testing correctly
> chore(*): a11y unit test script

- src/upload/upload.jsx
> fix(Upload): drag upload no trigger onDrop

- docs/cascader-select/demo/accessibility.md
- docs/cascader-select/demo/custom.md
- src/cascader-select/cascader-select.jsx
- test/cascader-select/a11y-spec.js
- test/cascader-select/index-spec.js
fixed https://github.com/alibaba-fusion/next/issues/407
> fix(CascaderSelect): support value not in data

- src/field/index.js
修复 field校验文件中"**getErrors**"方法漏绑this指向
> fix this binding method

- src/input/main.scss
- src/number-picker/main.scss
- src/select/auto-complete.jsx
- select value={0} display bug
- numberpicker inline input padding
> Fix select NumberPicker

- docs/transfer/demo/custom.md
- src/transfer/view/transfer-panel.jsx
> fix(Transfer): fix wrong Type of `title` props in `TransferPanel`

- docs/step/demo/basic.md
- docs/step/demo/controlled.md
- docs/step/demo/direction.md
- docs/step/demo/disable.md
- docs/step/demo/percent.md
- docs/step/theme/index.jsx
- src/step/scss/basic.scss
- src/step/view/step-item.jsx
- src/step/view/step.jsx
- test/step/index-spec.js
1. remove aria-label attribute from demo docs
2. support keyboard to control focus element
3. use semantic label
> feat(Step): support keyborad direction and use semantic label

- docs/select/demo/basic.md
- src/select/select.jsx
> fix(Select): use mouse to select text. Close #469

- src/range/main.scss
去掉之前 [PR](https://github.com/alibaba-fusion/next/pull/282) 里不必要的高度设置
> fix(Range): revert unnecessary style change

- docs/transfer/demo/accessibility.md
- src/menu/view/checkable-item.jsx
- src/search/Search.jsx
- src/step/view/step.jsx
- src/transfer/view/transfer-panel.jsx
- src/transfer/view/transfer.jsx
- src/util/htmlId.js
- src/util/index.js
- test/cascader-select/a11y-spec.js
- test/cascader/a11y-spec.js
- test/menu/a11y-spec.js
- test/search/a11y-spec.js
- test/search/index-spec.js
- test/step/a11y-spec.js
- test/step/index-spec.js
- test/tag/a11y-spec.js
- test/timeline/a11y-spec.js
- test/transfer/a11y-spec.js
- test/transfer/index-spec.js
- test/util/htmlId-spec.js
- added util to generate html ids
- add ids to connect labels and inputs for search and checkbox elements
- other a11y unit tests
> test(*): id generation for a11y and other a11y tests

- src/menu/view/menu.jsx
- test/menu/index-spec.js
related to https://github.com/alibaba-fusion/next/issues/475
> fix(Menu): filter duplicate keys

- src/table/main.scss
- src/table/scss/variable.scss
涉及到变量拆分，需要配置平台在升级y位前调用 @ali/next-variables-updater@1.1.1
> feat(Table): make header padding configurable

- src/rating/rating.jsx
> fix(Rating): remove form tag

- src/select/auto-complete.jsx
- test/select/index-spec.js
单测似乎对 keydown 支持不友好，demo 里面使用正常
> fix(Select): AutoComplete can input space with popupContent. Close #500

- docs/radio/theme/index.jsx
- src/radio/main.scss
- src/radio/scss/variable.scss
1. Display configured label color
2. Add separate border config for disabled checked/unchecked state
> fix(Radio): add configurations

- test/menu/a11y-spec.js
- test/nav/a11y-spec.js
- test/split-button/a11y-spec.js
- test/virtual-list/a11y-spec.js
- fix inaccurate menu tests
- add nav - skip popup subnav
- add splitButton - skip all
- add virtualList
> test(*): a11y unit tests

- .eslintrc
- a11y.eslintrc
- package.json
- add eslint jsx a11y plugin
- set all tests to "warn" to have it not prevent build
> style(*): eslint a11y warnings

- src/tag/main.scss
- src/tag/scss/mixin.scss
- src/tag/scss/variable.scss
Add content min width
https://udemo.alibaba-inc.com/preview#/preview/1167096/latest/iframe
- values were adjusted to be multiples of 4 to match our sizing pattern
> feat(Tag): add content min width theme variable

- docs/tab/index.en-us.md
- src/tab/tab.jsx
> fix(Tab): adding api document

- src/search/main.scss
> fix(Search): search config bug

- docs/balloon/demo/basic.md
- src/balloon/balloon.jsx
- src/balloon/tooltip.jsx
- src/balloon/util.js
- test/balloon/balloon-spec.js
- test/balloon/tooltip-spec.js
> fix(Balloon): popup won\'t goaway when hover out of disabled Button

- docs/form/demo/accessibility.md
> docs(Form): form a11y use docs

- src/collapse/main.scss
- src/collapse/scss/variable.scss
[x] - added changes to `next-variables-updater`
> feat(Collapse): add title hover theme variables

- src/form/form.jsx
- src/grid/col.jsx
- src/grid/row.jsx
- test/form/index-spec.js
- test/grid/index-spec.js
support Row,Form component(function)
> support Row,Form component(function)

- docs/dialog/theme/index.jsx
- src/dialog/main.scss
- src/dialog/scss/variable.scss
- src/dialog/show.jsx
- test/dialog/index-spec.js
- add theme variables to set alert dialog padding separate form dialog
- refactor dialog show to allow for placing in theme config docs
> [WIP] feat(Dialog): alert dialog padding

- src/upload/dragger.jsx
- src/upload/list.jsx
- src/upload/main.scss
- src/upload/scss/variable.scss
> feat(Upload): add card and drag confingurable item and disabled status

- docs/select/demo/combobox.md
> docs(Select): add select autocomplete doc

- src/tab/tabs/nav.jsx
Add back the line deleted in this pr https://github.com/alibaba-fusion/next/pull/464/files , to solve the closable issue
> fix(Tab): issues of closable

- src/tree/view/tree.jsx
fixed https://github.com/alibaba-fusion/next/issues/564
> fix(Tree): error when checkKey not in dataSource

- src/tag/main.scss
- src/tag/scss/placeholder.scss
- src/tag/scss/variable.scss
- add new variables for primary types
- remove unused variables
> feat(Tag): primary theme customization

- src/tab/tabs/nav.jsx
- test/tab/index-spec.js
Remove the impact of animation when initialize tab. Closing #586
> fix(Tab): wrong initial position due to animation

- src/loading/index.jsx
- src/loading/main.scss
- test/loading/index-spec.js
- transform unnecessary when using Overlay
> fix(Loading): fix offset for fullscreen

- docs/overlay/demo/controlled.md
Demo to show how to resolve Issue https://github.com/alibaba-fusion/next/issues/301
> docs(Overlay): demo for pair controlled popups

- src/step/view/step.jsx
- test/step/index-spec.js
> fix(Step): step keydown event bubble bug

- docs/table/index.en-us.md
- docs/table/index.md
- src/table/list-header.jsx
- src/table/list/row.jsx
- test/table/issue-spec.js
- API named useFirstLevelDataWhenNoChildren
> fix(Table): add deprecated API to make 0.x 1.x behave the same

- docs/date-picker/demo/accessibility.md
- docs/form/demo/accessibility.md
- docs/switch/demo/accessibility.md
Addresses Form A11y issue #542
> docs(*): a11y docs for form, datePicker, switch

- README.zh-cn.md
- site/zh-cn/theme.md
- src/menu/view/menu.jsx
- add docs close #629 close #631 
- empty focus key using undefined instead of ''
> fix(Menu),docs(*): add theme docs, close #629 

- src/table/fixed.jsx
> fix(Table): maxBodyHeight should be px

- src/select/auto-complete.jsx
- src/select/base.jsx
- src/select/select.jsx
1. 修复远程数据源下高亮第一个item
2. 后面会逐渐抛弃 base, 最终要把 auto-complete 独立成组件。这次先去除 componentWillReceiveProps 的公用
> fix(Select): hight first item with remote datasource. Close #654

- docs/form/demo/validate-custom-error.md
- src/field/index.js
- src/field/utils.js
- test/field/index-spec.js
- test/field/options-spec.js
- test/field/rules-spec.js
- test/field/utils-spec.js
- docs(Form): custom validation error
- test(Field): `getErrorStrs` tests, clean up eslint errors in other tests
- close #648
>  fix(Field): no react key props for errors

- src/input/textarea.jsx
* value.length !== maxLength  in ie/safari(mac) while value has `Enter`
* about maxLength compute: `Enter` was considered to be one char(\n) in chrome , but two chars(\r\n) in ie/safari(mac).
* so while value has `Enter`, we should let display length + 1
> fix(Input): maxLength in safari on Mac. Close #671

- src/step/scss/circle.scss
- src/step/scss/dot.scss
- src/step/scss/mixin.scss
- src/step/scss/variable.scss
> chore(*): step var split

- src/message/main.scss
- src/message/scss/mixin.scss
- src/message/scss/variable.scss
Reverts alibaba-fusion/next#689
> Revert "Message: split border radius variables"

- src/nav/main.scss
- src/nav/scss/mixin.scss
- src/nav/scss/variable.scss
There is no need to split variables.
3 feature:
- hover line width
- hover line color 
- hover font weight
they are of the same value before this pr,  no matter what kind of type there are(primary, secondary, line, normal).
> feat(Nav): add theme configuration about hover

- src/menu-button/index.jsx
- test/menu-button/index-spec.js
selectMode = 'multiple'
fixed https://github.com/alibaba-fusion/next/issues/662
> fix(Message): can`t close after click

- src/transfer/main.scss
- src/transfer/scss/variable.scss
- src/transfer/view/transfer.jsx
- test/transfer/index-spec.js
> feat(Transfer): make footer shadow configurable

- src/number-picker/main.scss
> fix(NumberPicker): UI for button height not eq input

- docs/upload/index.md
- src/upload/main.scss
- src/upload/scss/variable.scss
> [WIP]: Feat/upload var add

- src/tab/main.scss
Use existing variable `$tab-capsule-tab-border-line-color-hover`
> feat(Tab): make capsure border hover configurable

- package.json
- types/balloon/index.d.ts
- types/cascader-select/index.d.ts
- types/date-picker/index.d.ts
- types/menu-button/index.d.ts
- types/search/index.d.ts
- types/select/index.d.ts
- types/slider/index.d.ts
- types/table/index.d.ts
- types/time-picker/index.d.ts
- types/tree-select/index.d.ts
Some Typescript definitions is broken, this pr fixed it
> Fix Multiple Typescript Definitions

- src/calendar/range-calendar.jsx
- src/cascader-select/cascader-select.jsx
- src/select/index.jsx
Close:
https://github.com/alibaba-fusion/next/issues/758
https://github.com/alibaba-fusion/next/issues/694
> Fix DatePicker & CascaderSelect Bug

- src/table/tree/cell.jsx
> fix(Table): resizeable won't work if isTree on, close #384

- src/tab/tabs/nav.jsx
- test/tab/index-spec.js
Another buggy prone feature, all existing tests passed, but still requires review in detail.
> feat(Tab): support auto scroll to active tab

- docs/field/demo/seterror.md
- src/field/index.js
- test/field/index-spec.js
- show manually set errors in validate
- combine manually set errors and validation from rules
- rules errors override manually set errors when same input
> fix(Field): setError valiate - #close 747

- src/dialog/main.scss
- src/dialog/scss/variable.scss
> feat(Dialog): spacing between buttons theme var

- docs/radio/demo/useWithGrid.md
- src/checkbox/main.scss
- src/radio/main.scss
- src/radio/radio-group.jsx
- test/radio/a11y-spec.js
set default cursor to 'pointer'
> fix(Radio): change default cursor to pointer

- src/step/scss/circle.scss
保持Percent step 中 progress node 的 border 和 step 其他 node 的 border 一致;
> feat(Step): fix #796

- src/tree/view/tree.jsx
https://riddle.alibaba-inc.com/riddles/8b2b1729
> temp(*): fix tree pos off undefined

- src/tree/view/tree.jsx
> fix(Tree): dataSource will update indeterminateKeys

- src/tree/view/util.js
https://riddle.alibaba-inc.com/riddles/8b2b1729
> fix(Tree): set checkedStrategy check error

- src/form/item.jsx
- test/form/index-spec.js
get ref from component.ref, not component.props.ref
> fix(Form): use ref in FormItem. Close #820

- src/cascader/main.scss
- src/tree/view/tree-node.jsx
- src/tree/view/tree.jsx
- test/tree/index-spec.js
fix(Tree): cancel select on click twice
> Fix CascaderSelect & Tree Bugs

- src/nav/main.scss
> fix(Nav): disabled background should be the same with others

- docs/badge/demo/change.md
- docs/badge/index.en-us.md
- docs/badge/index.md
- src/badge/index.jsx
- src/badge/sup.jsx
- test/badge/index-spec.js
> feat(Badge): add API showZero, close #848

- src/badge/sup.jsx
> fix(Badge): change count to -1 error, close #845

- package.json
- src/overlay/utils/position.js
> Fix overlay position

- docs/radio/theme/index.jsx
Set Radio state to be the same with the state to be demoed
> fix(Radio): change demo default state

- src/field/index.js
- test/field/options-spec.js
- add better falsy value checks to allow 0 in constructor and init
> fix(Field): falsy values: fix #897

- src/cascader-select/cascader-select.jsx
- test/cascader-select/index-spec.js
not exist value  be removed after checked 
close #934
用户自定义传入value的，不在dataSource中的数据，也要能通过onChange吐出来
> fix(CascaderSelect): not exist value  be removed

- src/dialog/show.jsx
> fix(Dialog): pass event to onClose of Dialog.show

- docs/date-picker/demo/show-time.md
- src/date-picker/range-picker.jsx
- test/date-picker/index-spec.js
fixed https://github.com/alibaba-fusion/next/issues/433
fixed https://github.com/alibaba-fusion/next/issues/891
> feat(DatePicker): support set Array defaultValue

- src/menu/view/group.jsx
- src/menu/view/item.jsx
- src/menu/view/menu.jsx
- src/menu/view/popup-item.jsx
- src/menu/view/sub-menu.jsx
- test/menu/index-spec.js
- close #952 
- 支持在任意subMenu层级上自定义mode inline/popup
> fix(Menu): paddingLeft should only be related to inline mode

- src/menu/view/sub-menu.jsx
- src/nav/scss/mixin.scss
- test/nav/index-spec.js
> fix(Nav): subNav should be selected if it has selected child, close #520

- src/transfer/view/transfer-item.jsx
> fix(Transfer): fix that Transfer component cannot be dragged in firefox

- src/input/base.jsx
- test/input/index-spec.js
- test/input/textarea-spec.js
https://codepen.io/aboutblank/pen/JjPYrGj?editors=0010
> fix(Input): support null to reset value

- src/checkbox/checkbox.jsx
> fix(Checkbox): checkbox will update indeterminate state when in group

- src/overlay/main.scss
Reverts change used to fix https://github.com/alibaba-fusion/next/issues/812. 
This is not needed anymore due to change to fix https://github.com/alibaba-fusion/next/issues/887.
> fix(Overlay): remove position absolute. fix #1016

- src/tab/main.scss
> fix(Tab): use visibility instead of display to control tab content show.

- docs/table/theme/index.jsx
- src/table/base.jsx
- src/table/expanded.jsx
- src/table/main.scss
- src/table/scss/variable.scss
- src/table/selection.jsx
- types/table/index.d.ts
close https://github.com/alibaba-fusion/next/issues/1032
> feat(Table): add small size

- src/tab/tab.jsx
- src/tab/tabs/nav.jsx
- transform activeKey to string.
> fix(Tab): all key should use string

- src/tab/main.scss
- src/tab/scss/mixin.scss
- src/tab/scss/variable.scss
> fix(Tabs): fix tab nav and panel style

- docs/dialog/demo/large-content.md
- src/dialog/dialog.jsx
- src/dialog/main.scss
- src/overlay/main.scss
- src/overlay/overlay.jsx
- src/overlay/scss/variable.scss
* fix(Dialog): fullscreen mask click. fix #927
> fix(Dialog): fullscreen mask click. fix #927 (#932)

- types/collapse/index.d.ts
> typescript(Collapse): add expandedKeys for onExpand

- docs/search/demo/filter.md
> fix(Search): filter attr setting default value

- src/pagination/main.scss
fixed https://github.com/alibaba-fusion/next/issues/1037
> fix(Pagination): pagination size select  over width

- src/select/select.jsx
> fix(Select): cascader-select component  hasclear attr

- src/rating/main.scss
- src/rating/rating.jsx
- test/rating/index-spec.js
> fix(Rating): fix wrong behave in half mode

- src/select/base.jsx
> fix(Select): fix popup width. close #1075

- src/overlay/utils/position.js
due to https://github.com/alibaba-fusion/next/commit/7d87e86
> fix(Overlay): wrong object of reference in safari

- src/number-picker/main.scss
- src/number-picker/scss/variable.scss
> fix(NumberPicker): add variable for button corner. close #1151

- docs/time-picker/demo/format.md
- src/date-picker/date-picker.jsx
- src/date-picker/range-picker.jsx
- src/time-picker/panel.jsx
- src/time-picker/scss/panel.scss
- src/time-picker/time-picker.jsx
> fix(TimePicker): support format HH

- docs/input/demo/passwd.md
- src/input/index.jsx
- src/input/main.scss
- src/input/password.jsx
- src/input/scss/variable.scss
> Input: add background for error, add Input.Password

- src/checkbox/main.scss
- src/radio/main.scss
> fix(Radio): remove radio focus style

- src/upload/main.scss
fixed https://github.com/alibaba-fusion/next/issues/1207
> fix(Upload): outline error

- src/balloon/balloon.jsx
- src/balloon/tooltip.jsx
> fix(Balloon): Tooltip shoule support alignEdge

- src/upload/runtime/iframe-uploader.jsx
修复IE9 beforeUpload 支持不完善的问题。(目前已经把能兼容的兼容好呢)
Fix IE9 beforeUpload not support
> fix(Upload):ie9 beforeupload

- src/upload/runtime/iframe-uploader.jsx
fix upload to oss fail at ie9 env
> Fix(Upload): ie9 oss upload

- src/upload/runtime/iframe-uploader.jsx
Fix
- file overwrite
- iframe name not unique
> fix(Upload): iframe name not unique

- src/affix/index.jsx
- test/affix/index-spec.js
> fix(Affix): fix recursive call in some situation

- src/button/main.scss
> fix(Button): style vertical align middle

- src/rating/rating.jsx
> feat(Rating): update lifecycle

- src/affix/index.jsx
> feat(Affix): update lifecycle

- docs/tag/demo/colorful-tag.md
- docs/tag/index.en-us.md
- docs/tag/index.md
- src/tag/main.scss
- src/tag/scss/mixin.scss
- src/tag/scss/variable.scss
- src/tag/tag.jsx
- test/tag/index-spec.js
- types/tag/index.d.ts
can set custom tag color  by adding color property.
eg:
```jsx
<Tag color="blue" type="primary">blue</Tag>
```
> feat(Tag): support custom color

- src/menu/view/menu.jsx
> fix(Menu): group and its children should have the same inlineLevel

- src/table/base/body.jsx
- src/table/lock.jsx
- src/table/virtual.jsx
close https://github.com/alibaba-fusion/next/issues/1307
> fix(Table): correct rowIndex when useVirtual

- docs/cascader/demo/multiple.md
- src/cascader/cascader.jsx
- src/cascader/utils.js
- src/date-picker/date-picker.jsx
- src/date-picker/month-picker.jsx
- src/date-picker/range-picker.jsx
- src/date-picker/year-picker.jsx
- src/time-picker/time-picker.jsx
- src/tree-select/main.scss
- test/cascader/index-spec.js
> Fix Bugs, Close #1338, #1337, #1333

- types/checkbox/index.d.ts
- types/field/index.d.ts
补充Field和checkboxGroup的ts types
> feat(d.ts): add  Field and checkboxGroup's types

- src/nav/main.scss
- src/nav/scss/mixin.scss
embeddable嵌入模式下没有任何边框，计算边距时需要剔除
> fix(Nav): remove border-width when embeddable

- src/calendar/scss/table.scss
- src/calendar/scss/variable.scss
- src/cascader/main.scss
- src/cascader/scss/variable.scss
- src/input/scss/mixin.scss
- src/number-picker/main.scss
- src/number-picker/scss/variable.scss
- src/transfer/main.scss
- src/transfer/scss/variable.scss
> Feat variables

- src/calendar/calendar.jsx
- src/calendar/head/date-panel-header.jsx
- src/calendar/head/menu.jsx
- src/calendar/scss/header.scss
- src/calendar/utils/index.js
- src/date-picker/date-picker.jsx
disableChangeMode 测试版本，测试用例和文档后续完善再补
> Feat date picker header

- src/balloon/balloon.jsx
- src/box/index.jsx
- src/responsive-grid/index.jsx
```
<Box spacing={5}>
<ResponsiveGrid gap={10} style={{color: 'red'}}> </ResponsiveGrid>
</Box>
```
修复了上述模式下 gap不生效的bug
> fix(Balloon): infinite loop

- src/input/base.jsx
> fix(Input): stop bubble. close #1417

- types/upload/index.d.ts
> fix upload.card onchange TS

- src/table/fixed/header.jsx
用户可能出现js升级但是样式没升级的情况，通过style上复写样式，提高优先级
> chore(Table): add inline style

- src/upload/main.scss
> fix(Upload): progressbar layout exception in fusion-cool tool

- src/table/base/body.jsx
http://riddle.alibaba-inc.com/riddles/322f427f
> fix(Table): primaryKey is 0

- src/select/select.jsx
> fix(Select): add one key clear. close #1422

- src/number-picker/number-picker.jsx
1. https://riddle.alibaba-inc.com/riddles/76a1d8c7   Number 初始化的 value 是 null 的话可以输入中文
2. https://riddle.alibaba-inc.com/riddles/55e428c3 在使用 NumberPicker组件的时候遇到了一个问题
输入1.02，从末位删除"2"时，会自动转换为1，会把末两位0和2都删除掉，不能只删除掉末位
> Fix numberpicker 0.01 => 0.0 删除最后一位问题

- docs/upload/demo/card.md
- src/upload/main.scss
fix https://github.com/alibaba-fusion/next/issues/1531
> fix(Upload): compatibility in ie/firefox fix #1531

- src/overlay/gateway.jsx
- src/overlay/overlay.jsx
- src/overlay/position.jsx
- src/overlay/utils/find-node.js
- src/table/lock.jsx
in react16.6.1 ~ react 16.9 , findDomNode in React.Suspense throws error
https://github.com/facebook/react/issues/14188
> chore(*): add try catch to enhance robotness

- src/step/view/step.jsx
> feat(Step): update lifecycle

- src/transfer/view/transfer.jsx
> feat(Transfer): update lifecycle

- src/collapse/main.scss
- src/collapse/panel.jsx
- test/collapse/index-spec.js
> fix(Collapse): collapsed panel should be overflow hidden, close #1569

- package.json
- src/responsive-grid/create-style.js
https://github.com/alibaba-fusion/next/issues/1584
> Add side effect

- src/overlay/gateway.jsx
- src/overlay/overlay.jsx
- src/overlay/popup.jsx
- src/overlay/position.jsx
update lifecycle of overlay according to #1012
> feat: update lifecycle of overlay

- src/rating/main.scss
- src/rating/rating.jsx
- src/rating/scss/variable.scss
> feat(Rating): make rating icon configurable

- docs/date-picker/demo/basic.md
- src/time-picker/time-picker.jsx
- test/time-picker/index-spec.js
修复时间选择器在`value`值不为空的时候输入不触发输入值的校验和更新的bug
> fix(TimePicker): resolve bugs on blur handler, close #1533

- src/transfer/main.scss
- src/transfer/scss/variable.scss
> feat(Transfer): make transfer simple move icon configurable

- docs/step/demo/controlled.md
- src/step/scss/dot.scss
- src/step/view/step-item.jsx
- src/step/view/step.jsx
> feat(Step): adjust while receive props

- src/overlay/overlay.jsx
- src/table/base.jsx
- src/table/expanded.jsx
- src/table/tree.jsx
- src/table/util.js
- test/dropdown/index-spec.js
- test/menu/index-spec.js
- test/overlay/index-spec.js
- test/slider/index-spec.js
目前 overlay/menu/ballon 的单测直接跑会有个别错误。但是再刷新就好了，感觉刷新可能执行的时机不一样。
> fix(Overlay): react lifecycle

- src/tree/view/tree-node.jsx
- test/tree/index-spec.js
> fix(Tree): stop dragover event propagation, close #1662

- src/number-picker/number-picker.jsx
> Fix number picker

- src/menu/scss/variable.scss
> chore(*): update menu icon

- src/menu/view/popup-item.jsx
- src/menu/view/sub-menu.jsx
- src/menu/view/util.js
这个函数是为了寻找，当前选中项的父元素，k2n参数中的pos都是0-1这种格式的string。例如0-1-2，它的父亲是0-1，它的孩子是0-1-2-n
而之前的判断逻辑里把0-1 也当成了0-10的父节点
> fix(Menu): 0-1 is not parent of 0-10, close #1701

- types/menu/index.d.ts
> fix🐛 (Menu) onOpen的ts声明

- src/tab/tabs/nav.jsx
- test/tab/index-spec.js
> fix(Tab): wait until animation end, close #1674

- src/responsive-grid/create-style.js
- src/util/object.js
- test/form/index-spec.js
- test/util/object-spec.js
close https://github.com/alibaba-fusion/next/issues/1718
> fix(Util): enhance robotness

- docs/tree/demo/control-check.md
- src/tree/view/tree.jsx
- src/tree/view/util.js
- test/tree/index-spec.js
- 修复标签重复问题
- 修复checkStrictly模式下，设置indeterminate无效的问题
> fix(TreeSelect): resolve repeated label issue, close #1633

- src/config-provider/index.jsx
- src/menu/view/util.js
- src/pagination/pagination.jsx
1. http会命中某些bu的代码检查
2. ConfigProvider本身也需要config化，来传递context链上的数据
before：
after:
> chore(*): enhance robotness

- src/date-picker/date-picker.jsx
- src/date-picker/main.scss
- src/date-picker/month-picker.jsx
- src/date-picker/range-picker.jsx
- src/date-picker/week-picker.jsx
- src/date-picker/year-picker.jsx
- src/input/input.jsx
- src/time-picker/main.scss
- src/time-picker/time-picker.jsx
> feat(Input): hint icon overlap

- src/nav/main.scss
修复Item在SubNav中line-height样式被覆盖的bug
> fix(Nav): resolve issue #215

- src/overlay/utils/position.js
- test/overlay/index-spec.js
https://riddle.alibaba-inc.com/riddles/b58b48a6
解决 1.19.7 版本 由 https://github.com/alibaba-fusion/next/pull/1473/files 引入的 container 不能为react component的问题
> fix(Overlay): bug container when react component

- src/step/view/step-item.jsx
- test/step/index-spec.js
> fix(Step): fix bug of label-horizontal mode

- types/cascader-select/index.d.ts
> 添加followTrigger?: boolean;

- src/balloon/balloon.jsx
- src/balloon/tooltip.jsx
- src/upload/main.scss
- src/upload/upload.jsx
> fix(Upload): add type incase of lowversion theme

- src/upload/card.jsx
fix(Upload): resolve Upload.Card isPreview not work, close#1847
> fix(Upload): resolve Upload.Card isPreview not work, close#1847

- src/overlay/utils/position.js
- test/overlay/index-spec.js
1.20 版本当trigger 为fixed的时候，弹窗的top left值为0
> fix(Overlay): should base on BaseElement`offset

- src/input/input.jsx
- src/input/password.jsx
- src/input/textarea.jsx
> Fix input ie9 bug

- src/button/view/button.jsx
- types/button/index.d.ts
- types/form/index.d.ts
> fix(Button): fix iconSize types

- src/overlay/overlay.jsx
- test/menu/index-spec.js
fix https://riddle.alibaba-inc.com/riddles/3937230e?mode=jsx
> fix(Overlay): dom should ready before onOpen

- src/input/base.jsx
- src/select/base.jsx
> fix(Select): AutoComplete input focus selectionStart close #1913

- src/transfer/view/transfer.jsx
https://riddle.alibaba-inc.com/riddles/5a82dbdd
> fix(Transfer): fix item of right panel can't be checked when ds changed

- src/table/base/filter.jsx
- test/table/index-spec.js
> fix(Table): filter under control

- src/tree/view/tree-node.jsx
- test/tree/index-spec.js
Tree组件编辑的时候需要组件键盘事件冒泡，close #1942
> fix(Tree): should stop stopPropagation keyboard event when editing node

- docs/date-picker/demo/disabled-date.md
- src/date-picker/range-picker.jsx
- test/date-picker/index-spec.js
DatePicker.RangePicker当type为year或month时候，disabledDate属性无效
> fix(DatePicker): disabledDate invalid when type year/month,close #1565

- docs/form/index.en-us.md
- docs/form/index.md
uform 链接点击进去已经变成 formily 了，直接在文档里面更新。
> docs: rename uform to formily

- scripts/build/export-api-schema.js
- scripts/build/transform.js
- types/locale/default.d.ts
- types/locale/en-us.d.ts
- types/locale/ja-jp.d.ts
- types/locale/zh-cn.d.ts
- types/locale/zh-hk.d.ts
- types/locale/zh-tw.d.ts
> fix(Typescript): correct d.ts

- docs/menu/demo/render-more.md
- src/menu/view/menu.jsx
- test/menu/index-spec.js
> fix(Menu): renderMore with className

- scripts/build/export-api-schema.js
- scripts/build/transform.js
- types/locale/default.d.ts
- types/locale/en-us.d.ts
- types/locale/ja-jp.d.ts
- types/locale/zh-cn.d.ts
- types/locale/zh-hk.d.ts
- types/locale/zh-tw.d.ts
Reverts alibaba-fusion/next#2023
> Revert "fix(Typescript): correct d.ts"

- src/menu/view/util.js
在某些用法下，可能会出现menu的children仍未更新（k2n没更新），但是key已经更新了的情况，这种用法下可能会出现`Cannot read property '_key' of undefined`的错误
> fix(Menu): enhance robotness

- src/tab/tabs/nav.jsx
fix Tab offset rendering error when setting css scale on parent elements
fix  #1928
> fix(Tab): offest exception when set translate scale, close #1928

- docs/upload/demo/paste.md
- docs/upload/demo/submit.md
- docs/upload/demo/validation.md
这三个demo有问题的，组件unmount的时候ref是null，需要判断一下ref&&ref.getInstance();
我们这边运行这几个demo的时候会报错。
> chore(Upload): fix demos

- src/card/card.jsx
- src/card/collapse-content.jsx
- test/card/index-spec.js
卡片内容高度设置为 `'auto'` 的时候应该能自适应内容的高度。
问题复现：<https://riddle.alibaba-inc.com/riddles/22631222>
复现步骤：
1. 通过输入框把 Content Height 先改成 10px
2. 然后再改成 auto，会发现卡片高度并没有变化
期望结果：再改成 auto 的时候，卡片高度应该能自适应内容高度
> fix(Card): 🐛 card height must fit content if contentHeight is 'auto'

- src/select/auto-complete.jsx
> fix(Select): remove useless code

- src/badge/main.scss
- src/badge/scss/variable.scss
> fix(Badge): fix badge count min-width

- src/calendar/head/date-panel-header.jsx
- src/calendar/head/month-panel-header.jsx
- src/calendar/head/range-panel-header.jsx
- src/calendar/head/year-panel-header.jsx
Calendar 里大量使用了 button ，而 button 默认的 type 为 "submit"，当在表单上下文中时会触发表单提交（Form 中 DatePicker 开启 followTrigger 时）
> fix(Calendar): set button type to button

- docs/range/theme/index.jsx
- src/range/scss/mixin.scss
fix: https://github.com/alibaba-fusion/next/issues/2207
> fix(Range): fix range position with custom range-size-m-scale-height

- src/number-picker/number-picker.jsx
> fix(NumberPicker): fix bug that cannot input 0 decimal's last position

- package.json
- scripts/build/generate-css-entry.js
- scripts/build/lintcss.js
fix: https://github.com/alibaba-fusion/next/issues/2209
目前只是增强构建期间的validate能力，通过warning来暴露非法css。
需要通过修改源码来修复这些warning。
> chore(*): improve css validate

- docs/dialog/demo/large-content.md
- types/balloon/index.d.ts
fix [issue#2232](https://github.com/alibaba-fusion/next/issues/2232)
> Fix daily 0929

- src/tree/view/tree-node.jsx
- src/tree/view/tree.jsx
> fix(Tree): string refs bug

- src/core/mask.scss
- src/overlay/overlay.jsx
- test/overlay/index-spec.js
close https://github.com/alibaba-fusion/next/issues/2277
> fix(Overlay): dom should ready when call onOpen & afterOpen evnet

- src/upload/runtime/request.jsx
> fix(Upload):解决图片裁剪上传，名称丢失的问题

- src/table/expanded/row.jsx
- src/table/main.scss
> fix(Table): border chaos when Table in ExpandTable, close #2053

- src/date-picker/range-picker.jsx
- test/date-picker/index-spec.js
fix(DatePicker): close issues #2198, #2129
> fix(DatePicker): some issues

- docs/step/demo/direction.md
- src/step/view/step-item.jsx
- src/step/view/step.jsx
- test/step/index-spec.js
> fix(Step): 修复 step 组件切换 direction 时布局错乱的 issue, close #2266

- src/checkbox/main.scss
> fix(Checkbox): wrong style in .disabled.focus, close #2280

- src/balloon/inner.jsx
- src/balloon/main.scss
- src/balloon/rtl.scss
- src/balloon/scss/mixin.scss
before:
正常模式下：
半透明模式下：
after:
正常模式下：
半透明模式下：
> feat(Balloon): update the way of drawing direction angle, close #2351

- src/animate/scss/_expand-entrances/_withFade.scss
- src/animate/scss/_expand-exits/_withFade.scss
- src/loading/main.scss
- src/nav/rtl.scss
- src/number-picker/main.scss
- src/range/scss/mixin.scss
- src/select/main.scss
> fix(*): fix warning of style

- types/radio/index.d.ts
Radio.Goup value 类型为`string | number | boolean`，onChange 第一个参数也应该支持`number | boolean`类型
> chore(raido): 修改Radio.Goup onChange 声明，参数支持boolean

- docs/list/demo/basic.md
- docs/list/demo/complex.md
- docs/list/demo/custom-loading.md
- docs/list/demo/empty.md
- docs/list/demo/loading.md
> update demos of List

- docs/list/demo/basic.md
- docs/list/demo/complex.md
- docs/list/demo/custom-loading.md
- docs/list/demo/empty.md
- docs/list/demo/loading.md
> docs(List): update demos of List

- docs/menu/theme/index.jsx
- src/menu/main.scss
- src/menu/scss/variable.scss
- src/nav/main.scss
> Feat menu padding config

- docs/time-picker-2/adaptor/index.jsx
- docs/time-picker-2/demo/basic.md
- docs/time-picker-2/demo/default-value.md
- docs/time-picker-2/demo/disabled.md
- docs/time-picker-2/demo/field.md
- docs/time-picker-2/demo/format.md
- docs/time-picker-2/demo/no-border.md
- docs/time-picker-2/demo/render-menu.md
- docs/time-picker-2/demo/size.md
- docs/time-picker-2/demo/step.md
- docs/time-picker-2/demo/value.md
- docs/time-picker-2/index.en-us.md
- docs/time-picker-2/index.md
- docs/time-picker-2/theme/index.jsx
- src/index.js
- src/time-picker-2/index.jsx
- src/time-picker-2/main.scss
- src/time-picker-2/module/panel-footer.jsx
- src/time-picker-2/module/time-menu.jsx
- src/time-picker-2/panel.jsx
- src/time-picker-2/rtl.scss
- src/time-picker-2/scss/menu.scss
- src/time-picker-2/scss/panel.scss
- src/time-picker-2/scss/variable.scss
- src/time-picker-2/style.js
- src/time-picker-2/time-picker.jsx
- src/time-picker-2/utils/index.js
> feat(TimePicker): support TimePicker2

- docs/step/demo/direction.md
- package.json
- src/step/view/step-item.jsx
- src/step/view/step.jsx
- test/step/index-spec.js
> fix(Step): auto resize while step content changed

- docs/loading/demo/accessibility.md
- docs/loading/demo/basic.md
- docs/loading/demo/indicator.md
- docs/loading/demo/size.md
- docs/loading/demo/state.md
- docs/loading/demo/tipAlign.md
- docs/loading/index.md
- src/loading/index.jsx
docs(Loading): polish Loading demo and api doc
> docs(Loading): polish Loading demo and api doc

- docs/notification/demo/icon.md
- docs/notification/demo/position.md
- docs/notification/demo/style.md
- docs/notification/demo/type.md
- docs/notification/demo/update.md
- docs/notification/index.md
docs(Notification): polish Notification demo docs
> docs(Notification): polish Notification demo docs

- docs/responsive-grid/demo/basic.md
- docs/responsive-grid/index.md
docs(ResponsiveGrid): polish responsoveGrid demo docs
> docs(ResponsiveGrid): polish responsoveGrid demo docs

- src/checkbox/main.scss
- src/checkbox/scss/variable.scss
fix(Checkbox): fix disabled checkbox label color, close#2231
> fix(Checkbox): fix disabled checkbox label color, close#2231

- src/table/virtual/body.jsx
只改了76 和 87 行代码，其他都是代码格式化。
分析见 #2475
> fix(Table): virtual table doubled height, close #2475

- src/number-picker/number-picker.jsx
> fix(NumberPicker): fix default type prop, close #2370

- types/config-provider/index.d.ts
> fix(ConfigProvider): add missed static methods types

- src/checkbox/main.scss
- src/form/enhance.jsx
1. 修改margin-left为margin-right，修复group换行不对齐，close #2478 ；
2. 增加label margin-right，修改Group中整体margin-right为12px，与radio表现一致，close #1541 。
> fix(Checkbox): fix some style problem, close #2478 #1541

- src/checkbox/checkbox-group.jsx
- src/checkbox/index.jsx
- src/radio/index.jsx
- src/radio/main.scss
- src/radio/radio-group.jsx
1. 增加 inline-block，修复折行label跟随点击框，close #1748  #2079 ；
2. 更改间距设置与radio一致，close #1541 ；
3. 单个radio只增加内部label的margin-right，跟随margin-left，不增加外部margin（否则折行不对齐），close #2379 。
> fix(Radio): fix some style problem, close #1748 #2079 #1541 #2379

- scripts/preview/loaders/index/demo-parser.js
- scripts/preview/loaders/index/render-creator.js
chore(*): update demo copy icon
> chore(*): update demo copy icon

- src/table/base/body.jsx
- src/tag/scss/variable.scss
primary closabled tag的border color没办法改变
> fix(Table): tableOuterWidth can be undefined

- scripts/server/tpls/partials/header.ejs
- scripts/upload-server.js
- src/menu/view/item.jsx
Select 自己在 Input 上实现了 Up/Down 事件，没有用 Menu 的原生能力，所以也不需要 focusable。
> fix(Menu): do not autoFocus highLight while focuable=false fix #2565

- types/message/index.d.ts
> fix(Message): types

- docs/tab/demo/size.md
- src/tab/main.scss
- src/tab/tab.jsx
- src/tab/tabs/nav.jsx
- remove line animation animation=false ;
- fix item position while slider; 
- update activeKey while child update
> fix(Tab): remove line animation animation=false ; fix item position while slider; update activeKey while child update

- src/date-picker/week-picker.jsx
https://momentjs.com/docs/#/displaying/format/
> fix(WeekPicker): format bug

- src/overlay/utils/position.js
https://riddle.alibaba-inc.com/riddles/bad1cdfe
> fix(Overlay): wrong container when followTrigger

- package.json
unable to resolve @alifd/meet-react@^1.0.0
> fix(package.json): resolve issue

- src/balloon/scss/mixin.scss
- src/checkbox/main.scss
- src/menu/main.scss
- test/date-picker2/index-spec.js
1. Menu 增强鲁棒性
2. checkbox的icon上下居中用vertical-align: text-top
> fix(Menu): enhance robotness, close #2680

- src/step/rtl.scss
- src/step/scss/circle.scss
- src/step/scss/dot.scss
- src/step/scss/variable.scss
> feat(Step): add node size config

- src/button/main.scss
- src/button/scss/mixin.scss
- src/overlay/utils/position.js
- src/tab/tabs/nav.jsx
- test/overlay/index-spec.js
tab 修复了这个可怕的demo  https://riddle.alibaba-inc.com/riddles/4ee1c0f
> Fix daily 0205

- docs/step/demo/basic.md
- docs/step/demo/direction.md
- docs/step/index.en-us.md
- docs/step/index.md
- src/step/view/step-item.jsx
- src/step/view/step.jsx
- test/step/index-spec.js
> feat(Step): support stretch

- types/dialog/index.d.ts
> fix(Dialog): closeMode types

- src/date-picker2/picker.jsx
- src/date-picker2/prop-types.js
- test/date-picker2/index-spec.js
https://riddle.alibaba-inc.com/riddles/a87dbb58
> fix(DatePicker): bug on isValueChanged

- src/transfer/view/transfer-panel.jsx
> fix(Transfer): fix wrong behavior of check-all while using search

- src/core/util/_mixin.scss
- src/pagination/pagination.jsx
- src/table/index.jsx
- types/message/index.d.ts
- types/pagination/index.d.ts
> fix(Paginaton): make autoWidth false, add selectProps, close #2720

- docs/date-picker2/demo/basic.md
- docs/date-picker2/demo/default-panel.md
- docs/date-picker2/demo/format.md
- docs/date-picker2/demo/noborder.md
- docs/date-picker2/demo/preset.md
- docs/date-picker2/demo/size.md
引用了 `import { useState } from 'react';` 之后需要手动引入`React` `ReactDOM` 不然在riddle中会报错
> fix(DatePicker): demo bug on riddle

- types/step/index.d.ts
> fix(Step): add stretch type

- src/checkbox/main.scss
This reverts commit 5a4e5b2a133a5688c5829a8d9623875c9b1683dd.
> fix(checkbox): correct checkbox icon

- src/tab/tabs/nav.jsx
fix(Tab): <button> should be type="button", close #2812
> fix(Tab):  submit form containning tab unexpectly

- src/number-picker/number-picker.jsx
- test/number-picker/index-spec.js
避免-.x被Number()自动修正为-0.x展示，避免-0被自动修正为0展示，修复 #2849 。
> fix(NumberPicker): fix some corrections, close #2849

- src/number-picker/number-picker.jsx
- test/number-picker/index-spec.js
inline与normal模式下trigger都将无法被键盘tab聚焦
> fix(NumberPicker): make trigger untabbable, close #2794

- types/upload/index.d.ts
> 补全webkitdirectory代码提示

- docs/step/demo/step-process-failed.md
> fix(Step): update step demo(step-process-failed)

- src/switch/main.scss
https://github.com/alibaba-fusion/next/issues/2896
> fix(Switch): set Switch user-select: none

- src/calendar/head/range-panel-header.jsx
- src/calendar/range-calendar.jsx
- test/date-picker/index-spec.js
Datepicker2也有这个问题 @jerryyxu 关注下哦
> fix(DatePicker): interactive optimization, close #2951

- src/date-picker2/panels/date-panel.jsx
- src/date-picker2/panels/range-panel.jsx
- test/date-picker2/index-spec.js
> fix(DatePicker2): default time don`t work

- types/checkbox/index.d.ts
https://github.com/alibaba-fusion/next/blob/master/src/checkbox/checkbox.jsx#L89
https://github.com/alibaba-fusion/next/blob/master/src/checkbox/checkbox-group.jsx#L60
> fix(Checkbox): types

- src/number-picker/number-picker.jsx
- test/number-picker/index-spec.js
- 升级原因
✅ 数据订正逻辑紊乱，订正的准入卡口与时机安排不当，导致逻辑互相牵制，难以维护，容易修旧bug产生新bug
✅ 组件交互体验不顺畅，有非预期的订正行为，比如有些订正在blur生效，有些则直接通过无法键入实现，不统一
- 升级后交互区别
> feat(NumberPicker): refactor interactive logic 

- types/form/index.d.ts
> fix(Form.Item): add fullWidth type

- docs/overlay/demo/popup.md
- src/config-provider/config.jsx
- ConfigProvider requires popupContainer should also work for Overlay&Popup
> fix(Overlay): popupContainer won\'t work in Overlay&Popup

- types/number-picker/index.d.ts
> docs(NumberPicker): update ts types

- src/message/main.scss
Reverts alibaba-fusion/next#3060
> Revert "fix(Message): quick mode should be fixed, close #3059"

- docs/table/demo/style.md
- src/table/base/cell.jsx
- src/table/base/header.jsx
- src/table/column.jsx
- src/table/main.scss
用户可以通过column.wordBreak来控制各个列的word-break
fix: https://github.com/alibaba-fusion/next/issues/3148
> feat(Table): table column support wordBreak config

- src/number-picker/number-picker.jsx
修复NumberPicker：
1）空时，上下按钮无效
2）通过输入法限制修复 #3110
> fix(NumberPicker): step should work on undefined and win10 bug, close #3110

- src/overlay/popup.jsx
- test/overlay/index-spec.js
#3233 
**src/overlay/popup.jsx**
Core modification in `row 326`, other modifications come from the code formatting tool.
**test/overlay/index-spec.js**
add test unit.
> fix(Overlay): resolve crash when Popup receives an empty node

- docs/message/demo/toast-quick-v2.md
- src/core/form-element.scss
- src/message/index.jsx
- src/message/toast2.jsx
- test/message/index-spec.js
> fix(Form): form label previewfor theme config

- docs/avatar/adaptor/index.jsx
- docs/button/adaptor/index.jsx
- docs/checkbox/adaptor/index.jsx
- docs/input/adaptor/index.jsx
- docs/split-button/adaptor/index.jsx
Feature Description
修改 button/avatar/checkbox/split-button/input组件的adapter代码，支持返回将配置属性转化为组件属性
> feat(*): expose componet props for adapter

- docs/upload/demo/oss.md
- package.json
- scripts/preview/middlewares/get-variables.js
- scripts/server/middlewares/get-variables.js
- scripts/server/tpls/config.ejs
- src/input/main.scss
- src/input/scss/variable.scss
> [WIP] feat(Input): add $input-feedback-error-color=$input-text-color

- src/rating/rating.jsx
> fix(Rating): prevent default for a11y input

- package.json
- src/date-picker2/picker.jsx
> fix(DatePicker): should not close popup while click input

- types/balloon/index.d.ts
> fix(Balloon): add v2 typings to BalloonProps

- src/step/view/step-item.jsx
- src/util/dom.js
> fix(Step): fix wrong step body width in vertical mode

- src/button/scss/variable.scss
修复 css variable 变量问题 https://github.com/alibaba-fusion/next/issues/3584
> fix(Button): sass of rgba in css var fix #3584

- docs/dialog/demo/accessibility.md
- docs/dialog/demo/basic.md
- package.json
- src/dialog/dialog-v2.jsx
- src/dialog/scroll-locker.js
- test/dialog/index-v2-spec.js
修复3个问题：
1. hasMask 不工作的bug
2. 弹窗关闭的时候还原 body.style
- 解决思路：通过锁的方式，确保一定是栈的形式回复 body.style 就不会有问题
3. esc 时候一个一个的关闭
- 解决思路：所有的弹窗都要在展开的时候把自己的注册给父弹窗，让父弹窗知道自己有几个子弹窗，这样esc 的时候只要看看子弹窗还在不在，只要在就不允许关闭就行。
> fix(Dialog): hasMask not work / rollback body.style while hidden / esc one by one for v2

- src/dialog/scroll-locker.js
- src/util/dom.js
1. Dialog 关闭忘了清除缓存数据，以前没发现问题是因为没测试 Dialog 嵌套 Dialog。这块单测目前不好写容易报错
2. document.body 如果已经写了 overflow: hidden，我认为一定是没有滚动条的
> fix(Dialog): lockcache pop

- docs/drawer/demo/basic.md
- docs/drawer/demo/double.md
- docs/drawer/demo/placement.md
- docs/drawer/demo/quick.md
- docs/drawer/demo/select.md
- docs/drawer/demo/size.md
- docs/drawer/index.en-us.md
- docs/drawer/index.md
- src/dialog/scroll-locker.js
- src/drawer/drawer-v2.jsx
- src/drawer/drawer.jsx
- src/drawer/index.jsx
- src/drawer/inner.jsx
- src/drawer/main.scss
- src/drawer/show.jsx
- test/drawer/index-v2-spec.js
- test/overlay/index-v2-spec.js
- types/drawer/index.d.ts
1. css 布局
2. 支持 Drawer.show 快捷调用
> feat(Drawer): v2 version 

- types/range/index.d.ts
> fix(Range): types

- src/transfer/view/transfer.jsx
> fix(Transfer): fix some wrong prop-types of transfer

- src/tree/view/util.js
> fix: use Set to avoid duplication keys

- src/time-picker2/panel.jsx
> fix(TimePicker2): fix RangePicker wrong minutes and seconds disabled

- src/select/select.jsx
fix: https://github.com/alibaba-fusion/next/issues/3781
> fix(Select): make width stable

- src/breadcrumb/mobile/index.jsx
- src/shell/main.scss
- src/table/selection.jsx
跨端问题是这个： https://github.com/alibaba-fusion/next/commit/fa6fce97018b966ef89f33393058e229d3020969
> Fix daily 0316

- docs/select/theme/index.jsx
- src/table/tree.jsx
影响了1.25.25 26的tree异步加载demo的正常使用
> fix(Table): data should be mutable for async load

- src/calendar2/panels/header-panel.jsx
> fix(Calendar2): update header panel display value when panel value changed, close #3831

- src/slider/main.scss
- src/slider/scss/variable.scss
> fix(Slider): config for hover on dot fix #3839

- types/input/index.d.ts
- types/number-picker/index.d.ts
> 添加 Input、NumberPicker 使用 getInputNode 的函数签名

- docs/config-provider/demo/components.md
- src/locale/en-us.js
- src/locale/zh-cn.js
- src/locale/zh-hk.js
- src/locale/zh-tw.js
- src/time-picker2/time-picker.jsx
> fix(TimePicker2): fix FooterPanel ok button locale, close #3932

- src/icon/icon-font.jsx
- src/icon/icon.jsx
- src/icon/index.jsx
- test/icon/index-spec.js
This reverts commit 4e8fb51163b8eb96285208949e8689402e97cc23.
> Revert "fix(Icon): prefix of customIcon fix #3906"

- types/form/index.d.ts
onSubmit 应该有一个事件参数，支持 event.preventDefault() 等。实际组件是支持的，只是类型里没有标注。
> fix(types/form): onSubmit params

- types/balloon/index.d.ts
> fix(balloon): onVisibleChange add type

- src/select/base.jsx
- src/select/select.jsx
- test/select/index-spec.js
fix [Select]Select组件由编辑态变为预览态，显示内容发生改变 #4116
> fix(Select): Select组件变为预览态时，显示内容发生变化

- src/input/main.scss
- types/menu/index.d.ts
- types/nav/index.d.ts
> fix(Nav): nav optimize ts and update theme input-group style, close #4150

- src/overlay/index.jsx
> fix(Overlay): React does not recognize the  prop on a DOM element

- types/button/index.d.ts
支持以下用法在 TypeScript 中不报错：
```tsx
<Button type="primary" component={Link} to="/order/new">新增</Button>
```
> fix(Button): types support react-router Link as component

- types/badge/index.d.ts
> fix: badge typing

- src/time-picker2/main.scss
- src/time-picker2/module/date-input.jsx
> fix(TimePicker2): style of error state

- types/button/index.d.ts
> fix: button component type

- src/date-picker2/picker.jsx
fix(DatePicker2): onChange empty when value not ISO8601, close #4404
> fix(DatePicker2): onChange empty when value not ISO8601

- types/upload/index.d.ts
https://github.com/alibaba-fusion/next/issues/4442
> the ts type is missing close #4442

- src/input/input.jsx
> fix(Input): remove input propType onClear

- src/menu/view/item.jsx
- test/cascader/index-spec.js
- test/menu/index-spec.js
> fix(CascaderSelect): fail to scroll menu when changeOnSelect and expandTriggerType is hover, close #4423

- src/radio/radio-group.jsx
- src/radio/radio.jsx
- src/radio/with-context.jsx
- src/util/focus.js
- test/radio/group-spec.js
- test/radio/index-spec.js
> feat(Radio): add focus support for RadioGroup to #4461

- src/date-picker2/picker.jsx
- test/date-picker2/index-spec.js
> fix(DatePicker2): change inputValue when only mode changes

- docs/tree-select/demo/tree-path.md
- docs/tree-select/index.en-us.md
- docs/tree-select/index.md
- src/tree-select/tree-select.jsx
- test/tree-select/index-spec.js
> feat(TreeSelect): support special valueRender, close #4464

- docs/select/demo/virtual-select.md
- package.json
- src/select/base.jsx
- test/select/index-spec.js
> fix(Select): can infinite scroll when useVirtual, close #4175

- src/slider/slick/inner-slider.jsx
- src/slider/slick/mixins/helpers.js
- src/slider/slick/mixins/trackHelper.js
- test/slider/index-spec.js
> fix/(Slider): transform error #close 4302

- package.json
- types/select/index.d.ts
- types/tree-select/index.d.ts
> chore(TreeSelect): valueRender prop type

- src/upload/upload.jsx
- test/upload/file-list-spec.js
现有的upload组件无法隐藏上传列表，在listType属性上加了“none”参数来控制上传列表的显隐，默认显示上传列表。
Fixes  #4496
> feat(upload): add param to control upload list

- package.json
- test/overlay/index-spec.js
> fix(Overlay): support show-hide in nested scroll component

- docs/table/demo/dragable.md
> fix(Table): change the way to use of sortable

- src/table/base/cell.jsx
- test/table/issue-spec.js
> fix(Table): Modify the props of the title element in the table header

- src/slider/slick/inner-slider.jsx
- test/slider/index-spec.js
- test/slider/issue-spec.js
> fix(Slider): onChange does not affect activeIndex

- package.json
- test/balloon/issue-spec.js
> fix(Balloon): adjust overlay position at boundary when fixed

- src/message/scss/mixin.scss
- test/message/index-spec.js
- test/message/issue-spec.js
> fix(Message): when only content, vertical icon and content, issue#3910

- src/table/virtual.jsx
- test/table/issue-spec.js
> Fix issue 4394

- components/field/utils.js
- package-lock.json
> fix(Field): feat default scrollIntoView for firefox,#4288

- components/date-picker2/__tests__/index-spec.js
- components/date-picker2/panels/range-panel.jsx
- package-lock.json
> fix(DatePicker2): [DatePicker2] remove default range 24hr,close #3877

- components/table/__tests__/issue-spec.js
- components/table/new-lock.jsx
in locked columns, close #4264
> fix(Table): should support for should support for merging cells

- components/overlay/utils/position.js
- package-lock.json
- package.json
> fix(Overlay): fix the crash issue when resize is caused by adjustment, close #4692

- components/rating/main.scss
> fix(Rating): fix grade background

- components/util/component.ts
客户的环境有在 chrome 90 左右的，Object.hasOwn 从 chrome 93 开始支持
> fix(Util): compatibility breaking introduced by Object.hasOwn

- components/time-picker2/__tests__/index-spec.js
- components/time-picker2/main.scss
- components/time-picker2/time-picker.jsx
> fix(TimePicker2): TimePicker2 focusing issue  noborder, close #4657

- components/overlay/overlay.jsx
> fix(Overlay): shouldUpdatePosition when status=mounting, close #4740

- components/avatar/__tests__/index-spec.tsx
- components/avatar/index.tsx
> fix(Avatar): issue avatar size not working in box , close #3511

- components/date-picker2/__tests__/index-spec.js
- components/date-picker2/picker.jsx
> fix(DatePicker2): should pass inputProps to trigger function to support custom range picker trigger

- components/date-picker2/__tests__/index-spec.js
- components/date-picker2/index.jsx
- components/util/date.ts
> fix(DatePicker2): WeekPicker should format value correctly when date is 01-01, close #3727

- tools/build/webpack/prod.js
> fix(*): remove banner msg from dist/*.css to make @charset useful, close #3837

- components/select/__docs__/demo/tag/index.md
- components/select/__docs__/demo/tag/index.tsx
- components/select/__tests__/index-spec.js
- components/select/select.jsx
> feat(Select): selected option Tag suport colorful set with dataSource

- components/table/__tests__/issue-spec.js
- components/table/selection.jsx
> fix(Table): DataSource Id zero console.warning on Check ##3740

- components/cascader-select/__tests__/index-spec.js
- components/cascader-select/cascader-select.jsx
- components/cascader-select/index.jsx
> feat(CascaderSelect): support focus() and keyboard control, close #3608

- components/avatar/__docs__/index.en-us.md
- components/avatar/__docs__/index.md
- components/avatar/__tests__/index-spec.tsx
- components/avatar/index.tsx
- components/avatar/types.ts
> feat(Avatar): add imgProps for other props for img #3476

- README.md
> chore: add open with opensumi badge

- components/switch/__tests__/issue-spec.tsx
- components/switch/index.tsx
> fix(Switch): form fail to pass checked to Switch by wrong displayName, close #4819

- components/input/main.scss
> fix(Input): fix autoprefixer warning, close #4795

- components/select/__tests__/index-spec.tsx
- components/select/select.tsx
> fix(Select):  preserve previous data when selecting all, close #4810

- components/number-picker/__docs__/demo/mobile/index.md
- components/number-picker/__docs__/demo/mobile/index.tsx
- components/number-picker/__docs__/index.en-us.md
- components/number-picker/__docs__/index.md
- components/number-picker/number-picker.jsx
> fix(NumberPicker): adjust type behavior for phone/tablet devices

- components/tab/__tests__/index-spec.js
- components/tab/tabs/nav.jsx
> fix(Tab): should not be obscured if has extra

- components/cascader-select/__tests__/issue-spec.tsx
- components/cascader/__tests__/index-spec.tsx
- components/cascader/menu.tsx
> fix(CascaderSelect): Use white background with virtual scrolling

- components/tree/__tests__/index-spec.tsx
- components/tree/view/tree.tsx
close #2899 https://github.com/orgs/alibaba-fusion/projects/1/views/1?pane=issue&itemId=56279397
> fix(Tree): should keep click and key events consistent

- components/date-picker2/__tests__/index-spec.js
- components/date-picker2/picker.jsx
> fix(DatePicker2): Unable to enter space to enter time

- components/calendar/__tests__/index-spec.tsx
- components/calendar/__tests__/issue-spec.tsx
- components/calendar/calendar.tsx
- components/calendar/head/card-header.tsx
- components/calendar/head/date-panel-header.tsx
- components/calendar/types.ts
> fix(Calendar): make switch panel unclickable when showOtherMonth is false, close #4782

- components/upload/__tests__/card-spec.tsx
- components/upload/__tests__/index-spec.tsx
- components/upload/upload.tsx
> fix(Uplaod): support upload again when an upload fails, close #4849

- components/upload/__docs__/demo/extra/index.tsx
- components/upload/__docs__/index.en-us.md
- components/upload/__docs__/index.md
- components/upload/__tests__/index-spec.tsx
- components/upload/list.tsx
- components/upload/types.ts
- components/upload/upload.tsx
> fix(Upload): support itemRender on Dragger, close #4840

- components/form/__tests__/index-spec.js
- components/form/scss/mixin.scss
https://github.com/orgs/alibaba-fusion/projects/1?pane=issue&itemId=68642282
> fix(Form): enabled responsive form should maintain alignment between label and input

- components/select/__tests__/index-spec.tsx
- components/select/auto-complete.tsx
- components/select/data-store.ts
> fix(Select): adjust auto-complete menu length issue, close #4873

- components/config-provider/index.tsx
> refactor(ConfigProvider): static reference to  moment

- components/badge/__tests__/index-spec.tsx
- components/badge/main.scss
> fix(Badge): set alignment by use transform

- tools/serve/index.ts
chore(Tools): change components mian.scss import order when run the command npm run start
修改了本地开发是组件scss文件的引用顺序，和打包时的顺序保持一致，避免因为组件scss加载顺序导致样式上的差异
> chore(Tools): change components mian.scss import order when run the command npm run start

- components/field/__tests__/index-spec.tsx
- package-lock.json
- package.json
Field 组件在表单项未渲染的时候调用setError会导致生成的fieldMeta 中没有name字段，从而导致在执行init逻辑的时候，代理meta的时候，setvalue 会因为没有name字段而 覆盖field的values ，导致field的整体values出现异常
> fix(Field): fix use setError on uninitialized field caused incorrect values configuration

- .gitignore
- components/nav/__docs__/demo/auto-width/index.css
- components/nav/__docs__/demo/auto-width/index.md
- components/nav/__docs__/demo/auto-width/index.tsx
- components/nav/__tests__/index-spec.tsx
- components/nav/main.scss
- components/shell/__docs__/demo/complicated/index.tsx
- components/shell/__docs__/demo/header-global-local/index.tsx
- components/shell/__docs__/demo/header-global/index.tsx
- components/shell/__docs__/theme/index.tsx
fix(Nav): the icon is not centered when the width of Nav in iconOnly mode is less than the default width #3296
> fix(Nav): the icon is not centered when the width of Nav in iconOnly mode is less than the default width
